################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (14.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../FFT/Source/FilteringFunctions/FilteringFunctions.c \
../FFT/Source/FilteringFunctions/FilteringFunctionsF16.c \
../FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.c \
../FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.c \
../FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_f16.c \
../FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.c \
../FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.c \
../FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.c \
../FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.c \
../FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.c \
../FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.c \
../FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.c \
../FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.c \
../FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.c \
../FFT/Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.c \
../FFT/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.c \
../FFT/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.c \
../FFT/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.c \
../FFT/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.c \
../FFT/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.c \
../FFT/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.c \
../FFT/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.c \
../FFT/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.c \
../FFT/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.c \
../FFT/Source/FilteringFunctions/arm_conv_f32.c \
../FFT/Source/FilteringFunctions/arm_conv_fast_opt_q15.c \
../FFT/Source/FilteringFunctions/arm_conv_fast_q15.c \
../FFT/Source/FilteringFunctions/arm_conv_fast_q31.c \
../FFT/Source/FilteringFunctions/arm_conv_opt_q15.c \
../FFT/Source/FilteringFunctions/arm_conv_opt_q7.c \
../FFT/Source/FilteringFunctions/arm_conv_partial_f32.c \
../FFT/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.c \
../FFT/Source/FilteringFunctions/arm_conv_partial_fast_q15.c \
../FFT/Source/FilteringFunctions/arm_conv_partial_fast_q31.c \
../FFT/Source/FilteringFunctions/arm_conv_partial_opt_q15.c \
../FFT/Source/FilteringFunctions/arm_conv_partial_opt_q7.c \
../FFT/Source/FilteringFunctions/arm_conv_partial_q15.c \
../FFT/Source/FilteringFunctions/arm_conv_partial_q31.c \
../FFT/Source/FilteringFunctions/arm_conv_partial_q7.c \
../FFT/Source/FilteringFunctions/arm_conv_q15.c \
../FFT/Source/FilteringFunctions/arm_conv_q31.c \
../FFT/Source/FilteringFunctions/arm_conv_q7.c \
../FFT/Source/FilteringFunctions/arm_correlate_f16.c \
../FFT/Source/FilteringFunctions/arm_correlate_f32.c \
../FFT/Source/FilteringFunctions/arm_correlate_f64.c \
../FFT/Source/FilteringFunctions/arm_correlate_fast_opt_q15.c \
../FFT/Source/FilteringFunctions/arm_correlate_fast_q15.c \
../FFT/Source/FilteringFunctions/arm_correlate_fast_q31.c \
../FFT/Source/FilteringFunctions/arm_correlate_opt_q15.c \
../FFT/Source/FilteringFunctions/arm_correlate_opt_q7.c \
../FFT/Source/FilteringFunctions/arm_correlate_q15.c \
../FFT/Source/FilteringFunctions/arm_correlate_q31.c \
../FFT/Source/FilteringFunctions/arm_correlate_q7.c \
../FFT/Source/FilteringFunctions/arm_fir_decimate_f32.c \
../FFT/Source/FilteringFunctions/arm_fir_decimate_f64.c \
../FFT/Source/FilteringFunctions/arm_fir_decimate_fast_q15.c \
../FFT/Source/FilteringFunctions/arm_fir_decimate_fast_q31.c \
../FFT/Source/FilteringFunctions/arm_fir_decimate_init_f32.c \
../FFT/Source/FilteringFunctions/arm_fir_decimate_init_f64.c \
../FFT/Source/FilteringFunctions/arm_fir_decimate_init_q15.c \
../FFT/Source/FilteringFunctions/arm_fir_decimate_init_q31.c \
../FFT/Source/FilteringFunctions/arm_fir_decimate_q15.c \
../FFT/Source/FilteringFunctions/arm_fir_decimate_q31.c \
../FFT/Source/FilteringFunctions/arm_fir_f16.c \
../FFT/Source/FilteringFunctions/arm_fir_f32.c \
../FFT/Source/FilteringFunctions/arm_fir_f64.c \
../FFT/Source/FilteringFunctions/arm_fir_fast_q15.c \
../FFT/Source/FilteringFunctions/arm_fir_fast_q31.c \
../FFT/Source/FilteringFunctions/arm_fir_init_f16.c \
../FFT/Source/FilteringFunctions/arm_fir_init_f32.c \
../FFT/Source/FilteringFunctions/arm_fir_init_f64.c \
../FFT/Source/FilteringFunctions/arm_fir_init_q15.c \
../FFT/Source/FilteringFunctions/arm_fir_init_q31.c \
../FFT/Source/FilteringFunctions/arm_fir_init_q7.c \
../FFT/Source/FilteringFunctions/arm_fir_interpolate_f32.c \
../FFT/Source/FilteringFunctions/arm_fir_interpolate_init_f32.c \
../FFT/Source/FilteringFunctions/arm_fir_interpolate_init_q15.c \
../FFT/Source/FilteringFunctions/arm_fir_interpolate_init_q31.c \
../FFT/Source/FilteringFunctions/arm_fir_interpolate_q15.c \
../FFT/Source/FilteringFunctions/arm_fir_interpolate_q31.c \
../FFT/Source/FilteringFunctions/arm_fir_lattice_f32.c \
../FFT/Source/FilteringFunctions/arm_fir_lattice_init_f32.c \
../FFT/Source/FilteringFunctions/arm_fir_lattice_init_q15.c \
../FFT/Source/FilteringFunctions/arm_fir_lattice_init_q31.c \
../FFT/Source/FilteringFunctions/arm_fir_lattice_q15.c \
../FFT/Source/FilteringFunctions/arm_fir_lattice_q31.c \
../FFT/Source/FilteringFunctions/arm_fir_q15.c \
../FFT/Source/FilteringFunctions/arm_fir_q31.c \
../FFT/Source/FilteringFunctions/arm_fir_q7.c \
../FFT/Source/FilteringFunctions/arm_fir_sparse_f32.c \
../FFT/Source/FilteringFunctions/arm_fir_sparse_init_f32.c \
../FFT/Source/FilteringFunctions/arm_fir_sparse_init_q15.c \
../FFT/Source/FilteringFunctions/arm_fir_sparse_init_q31.c \
../FFT/Source/FilteringFunctions/arm_fir_sparse_init_q7.c \
../FFT/Source/FilteringFunctions/arm_fir_sparse_q15.c \
../FFT/Source/FilteringFunctions/arm_fir_sparse_q31.c \
../FFT/Source/FilteringFunctions/arm_fir_sparse_q7.c \
../FFT/Source/FilteringFunctions/arm_iir_lattice_f32.c \
../FFT/Source/FilteringFunctions/arm_iir_lattice_init_f32.c \
../FFT/Source/FilteringFunctions/arm_iir_lattice_init_q15.c \
../FFT/Source/FilteringFunctions/arm_iir_lattice_init_q31.c \
../FFT/Source/FilteringFunctions/arm_iir_lattice_q15.c \
../FFT/Source/FilteringFunctions/arm_iir_lattice_q31.c \
../FFT/Source/FilteringFunctions/arm_levinson_durbin_f16.c \
../FFT/Source/FilteringFunctions/arm_levinson_durbin_f32.c \
../FFT/Source/FilteringFunctions/arm_levinson_durbin_q31.c \
../FFT/Source/FilteringFunctions/arm_lms_f32.c \
../FFT/Source/FilteringFunctions/arm_lms_init_f32.c \
../FFT/Source/FilteringFunctions/arm_lms_init_q15.c \
../FFT/Source/FilteringFunctions/arm_lms_init_q31.c \
../FFT/Source/FilteringFunctions/arm_lms_norm_f32.c \
../FFT/Source/FilteringFunctions/arm_lms_norm_init_f32.c \
../FFT/Source/FilteringFunctions/arm_lms_norm_init_q15.c \
../FFT/Source/FilteringFunctions/arm_lms_norm_init_q31.c \
../FFT/Source/FilteringFunctions/arm_lms_norm_q15.c \
../FFT/Source/FilteringFunctions/arm_lms_norm_q31.c \
../FFT/Source/FilteringFunctions/arm_lms_q15.c \
../FFT/Source/FilteringFunctions/arm_lms_q31.c 

OBJS += \
./FFT/Source/FilteringFunctions/FilteringFunctions.o \
./FFT/Source/FilteringFunctions/FilteringFunctionsF16.o \
./FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.o \
./FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.o \
./FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_f16.o \
./FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.o \
./FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.o \
./FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.o \
./FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.o \
./FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.o \
./FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.o \
./FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.o \
./FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.o \
./FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.o \
./FFT/Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.o \
./FFT/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.o \
./FFT/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.o \
./FFT/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.o \
./FFT/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.o \
./FFT/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.o \
./FFT/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.o \
./FFT/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.o \
./FFT/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.o \
./FFT/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.o \
./FFT/Source/FilteringFunctions/arm_conv_f32.o \
./FFT/Source/FilteringFunctions/arm_conv_fast_opt_q15.o \
./FFT/Source/FilteringFunctions/arm_conv_fast_q15.o \
./FFT/Source/FilteringFunctions/arm_conv_fast_q31.o \
./FFT/Source/FilteringFunctions/arm_conv_opt_q15.o \
./FFT/Source/FilteringFunctions/arm_conv_opt_q7.o \
./FFT/Source/FilteringFunctions/arm_conv_partial_f32.o \
./FFT/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.o \
./FFT/Source/FilteringFunctions/arm_conv_partial_fast_q15.o \
./FFT/Source/FilteringFunctions/arm_conv_partial_fast_q31.o \
./FFT/Source/FilteringFunctions/arm_conv_partial_opt_q15.o \
./FFT/Source/FilteringFunctions/arm_conv_partial_opt_q7.o \
./FFT/Source/FilteringFunctions/arm_conv_partial_q15.o \
./FFT/Source/FilteringFunctions/arm_conv_partial_q31.o \
./FFT/Source/FilteringFunctions/arm_conv_partial_q7.o \
./FFT/Source/FilteringFunctions/arm_conv_q15.o \
./FFT/Source/FilteringFunctions/arm_conv_q31.o \
./FFT/Source/FilteringFunctions/arm_conv_q7.o \
./FFT/Source/FilteringFunctions/arm_correlate_f16.o \
./FFT/Source/FilteringFunctions/arm_correlate_f32.o \
./FFT/Source/FilteringFunctions/arm_correlate_f64.o \
./FFT/Source/FilteringFunctions/arm_correlate_fast_opt_q15.o \
./FFT/Source/FilteringFunctions/arm_correlate_fast_q15.o \
./FFT/Source/FilteringFunctions/arm_correlate_fast_q31.o \
./FFT/Source/FilteringFunctions/arm_correlate_opt_q15.o \
./FFT/Source/FilteringFunctions/arm_correlate_opt_q7.o \
./FFT/Source/FilteringFunctions/arm_correlate_q15.o \
./FFT/Source/FilteringFunctions/arm_correlate_q31.o \
./FFT/Source/FilteringFunctions/arm_correlate_q7.o \
./FFT/Source/FilteringFunctions/arm_fir_decimate_f32.o \
./FFT/Source/FilteringFunctions/arm_fir_decimate_f64.o \
./FFT/Source/FilteringFunctions/arm_fir_decimate_fast_q15.o \
./FFT/Source/FilteringFunctions/arm_fir_decimate_fast_q31.o \
./FFT/Source/FilteringFunctions/arm_fir_decimate_init_f32.o \
./FFT/Source/FilteringFunctions/arm_fir_decimate_init_f64.o \
./FFT/Source/FilteringFunctions/arm_fir_decimate_init_q15.o \
./FFT/Source/FilteringFunctions/arm_fir_decimate_init_q31.o \
./FFT/Source/FilteringFunctions/arm_fir_decimate_q15.o \
./FFT/Source/FilteringFunctions/arm_fir_decimate_q31.o \
./FFT/Source/FilteringFunctions/arm_fir_f16.o \
./FFT/Source/FilteringFunctions/arm_fir_f32.o \
./FFT/Source/FilteringFunctions/arm_fir_f64.o \
./FFT/Source/FilteringFunctions/arm_fir_fast_q15.o \
./FFT/Source/FilteringFunctions/arm_fir_fast_q31.o \
./FFT/Source/FilteringFunctions/arm_fir_init_f16.o \
./FFT/Source/FilteringFunctions/arm_fir_init_f32.o \
./FFT/Source/FilteringFunctions/arm_fir_init_f64.o \
./FFT/Source/FilteringFunctions/arm_fir_init_q15.o \
./FFT/Source/FilteringFunctions/arm_fir_init_q31.o \
./FFT/Source/FilteringFunctions/arm_fir_init_q7.o \
./FFT/Source/FilteringFunctions/arm_fir_interpolate_f32.o \
./FFT/Source/FilteringFunctions/arm_fir_interpolate_init_f32.o \
./FFT/Source/FilteringFunctions/arm_fir_interpolate_init_q15.o \
./FFT/Source/FilteringFunctions/arm_fir_interpolate_init_q31.o \
./FFT/Source/FilteringFunctions/arm_fir_interpolate_q15.o \
./FFT/Source/FilteringFunctions/arm_fir_interpolate_q31.o \
./FFT/Source/FilteringFunctions/arm_fir_lattice_f32.o \
./FFT/Source/FilteringFunctions/arm_fir_lattice_init_f32.o \
./FFT/Source/FilteringFunctions/arm_fir_lattice_init_q15.o \
./FFT/Source/FilteringFunctions/arm_fir_lattice_init_q31.o \
./FFT/Source/FilteringFunctions/arm_fir_lattice_q15.o \
./FFT/Source/FilteringFunctions/arm_fir_lattice_q31.o \
./FFT/Source/FilteringFunctions/arm_fir_q15.o \
./FFT/Source/FilteringFunctions/arm_fir_q31.o \
./FFT/Source/FilteringFunctions/arm_fir_q7.o \
./FFT/Source/FilteringFunctions/arm_fir_sparse_f32.o \
./FFT/Source/FilteringFunctions/arm_fir_sparse_init_f32.o \
./FFT/Source/FilteringFunctions/arm_fir_sparse_init_q15.o \
./FFT/Source/FilteringFunctions/arm_fir_sparse_init_q31.o \
./FFT/Source/FilteringFunctions/arm_fir_sparse_init_q7.o \
./FFT/Source/FilteringFunctions/arm_fir_sparse_q15.o \
./FFT/Source/FilteringFunctions/arm_fir_sparse_q31.o \
./FFT/Source/FilteringFunctions/arm_fir_sparse_q7.o \
./FFT/Source/FilteringFunctions/arm_iir_lattice_f32.o \
./FFT/Source/FilteringFunctions/arm_iir_lattice_init_f32.o \
./FFT/Source/FilteringFunctions/arm_iir_lattice_init_q15.o \
./FFT/Source/FilteringFunctions/arm_iir_lattice_init_q31.o \
./FFT/Source/FilteringFunctions/arm_iir_lattice_q15.o \
./FFT/Source/FilteringFunctions/arm_iir_lattice_q31.o \
./FFT/Source/FilteringFunctions/arm_levinson_durbin_f16.o \
./FFT/Source/FilteringFunctions/arm_levinson_durbin_f32.o \
./FFT/Source/FilteringFunctions/arm_levinson_durbin_q31.o \
./FFT/Source/FilteringFunctions/arm_lms_f32.o \
./FFT/Source/FilteringFunctions/arm_lms_init_f32.o \
./FFT/Source/FilteringFunctions/arm_lms_init_q15.o \
./FFT/Source/FilteringFunctions/arm_lms_init_q31.o \
./FFT/Source/FilteringFunctions/arm_lms_norm_f32.o \
./FFT/Source/FilteringFunctions/arm_lms_norm_init_f32.o \
./FFT/Source/FilteringFunctions/arm_lms_norm_init_q15.o \
./FFT/Source/FilteringFunctions/arm_lms_norm_init_q31.o \
./FFT/Source/FilteringFunctions/arm_lms_norm_q15.o \
./FFT/Source/FilteringFunctions/arm_lms_norm_q31.o \
./FFT/Source/FilteringFunctions/arm_lms_q15.o \
./FFT/Source/FilteringFunctions/arm_lms_q31.o 

C_DEPS += \
./FFT/Source/FilteringFunctions/FilteringFunctions.d \
./FFT/Source/FilteringFunctions/FilteringFunctionsF16.d \
./FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.d \
./FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.d \
./FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_f16.d \
./FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.d \
./FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.d \
./FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.d \
./FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.d \
./FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.d \
./FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.d \
./FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.d \
./FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.d \
./FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.d \
./FFT/Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.d \
./FFT/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.d \
./FFT/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.d \
./FFT/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.d \
./FFT/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.d \
./FFT/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.d \
./FFT/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.d \
./FFT/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.d \
./FFT/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.d \
./FFT/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.d \
./FFT/Source/FilteringFunctions/arm_conv_f32.d \
./FFT/Source/FilteringFunctions/arm_conv_fast_opt_q15.d \
./FFT/Source/FilteringFunctions/arm_conv_fast_q15.d \
./FFT/Source/FilteringFunctions/arm_conv_fast_q31.d \
./FFT/Source/FilteringFunctions/arm_conv_opt_q15.d \
./FFT/Source/FilteringFunctions/arm_conv_opt_q7.d \
./FFT/Source/FilteringFunctions/arm_conv_partial_f32.d \
./FFT/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.d \
./FFT/Source/FilteringFunctions/arm_conv_partial_fast_q15.d \
./FFT/Source/FilteringFunctions/arm_conv_partial_fast_q31.d \
./FFT/Source/FilteringFunctions/arm_conv_partial_opt_q15.d \
./FFT/Source/FilteringFunctions/arm_conv_partial_opt_q7.d \
./FFT/Source/FilteringFunctions/arm_conv_partial_q15.d \
./FFT/Source/FilteringFunctions/arm_conv_partial_q31.d \
./FFT/Source/FilteringFunctions/arm_conv_partial_q7.d \
./FFT/Source/FilteringFunctions/arm_conv_q15.d \
./FFT/Source/FilteringFunctions/arm_conv_q31.d \
./FFT/Source/FilteringFunctions/arm_conv_q7.d \
./FFT/Source/FilteringFunctions/arm_correlate_f16.d \
./FFT/Source/FilteringFunctions/arm_correlate_f32.d \
./FFT/Source/FilteringFunctions/arm_correlate_f64.d \
./FFT/Source/FilteringFunctions/arm_correlate_fast_opt_q15.d \
./FFT/Source/FilteringFunctions/arm_correlate_fast_q15.d \
./FFT/Source/FilteringFunctions/arm_correlate_fast_q31.d \
./FFT/Source/FilteringFunctions/arm_correlate_opt_q15.d \
./FFT/Source/FilteringFunctions/arm_correlate_opt_q7.d \
./FFT/Source/FilteringFunctions/arm_correlate_q15.d \
./FFT/Source/FilteringFunctions/arm_correlate_q31.d \
./FFT/Source/FilteringFunctions/arm_correlate_q7.d \
./FFT/Source/FilteringFunctions/arm_fir_decimate_f32.d \
./FFT/Source/FilteringFunctions/arm_fir_decimate_f64.d \
./FFT/Source/FilteringFunctions/arm_fir_decimate_fast_q15.d \
./FFT/Source/FilteringFunctions/arm_fir_decimate_fast_q31.d \
./FFT/Source/FilteringFunctions/arm_fir_decimate_init_f32.d \
./FFT/Source/FilteringFunctions/arm_fir_decimate_init_f64.d \
./FFT/Source/FilteringFunctions/arm_fir_decimate_init_q15.d \
./FFT/Source/FilteringFunctions/arm_fir_decimate_init_q31.d \
./FFT/Source/FilteringFunctions/arm_fir_decimate_q15.d \
./FFT/Source/FilteringFunctions/arm_fir_decimate_q31.d \
./FFT/Source/FilteringFunctions/arm_fir_f16.d \
./FFT/Source/FilteringFunctions/arm_fir_f32.d \
./FFT/Source/FilteringFunctions/arm_fir_f64.d \
./FFT/Source/FilteringFunctions/arm_fir_fast_q15.d \
./FFT/Source/FilteringFunctions/arm_fir_fast_q31.d \
./FFT/Source/FilteringFunctions/arm_fir_init_f16.d \
./FFT/Source/FilteringFunctions/arm_fir_init_f32.d \
./FFT/Source/FilteringFunctions/arm_fir_init_f64.d \
./FFT/Source/FilteringFunctions/arm_fir_init_q15.d \
./FFT/Source/FilteringFunctions/arm_fir_init_q31.d \
./FFT/Source/FilteringFunctions/arm_fir_init_q7.d \
./FFT/Source/FilteringFunctions/arm_fir_interpolate_f32.d \
./FFT/Source/FilteringFunctions/arm_fir_interpolate_init_f32.d \
./FFT/Source/FilteringFunctions/arm_fir_interpolate_init_q15.d \
./FFT/Source/FilteringFunctions/arm_fir_interpolate_init_q31.d \
./FFT/Source/FilteringFunctions/arm_fir_interpolate_q15.d \
./FFT/Source/FilteringFunctions/arm_fir_interpolate_q31.d \
./FFT/Source/FilteringFunctions/arm_fir_lattice_f32.d \
./FFT/Source/FilteringFunctions/arm_fir_lattice_init_f32.d \
./FFT/Source/FilteringFunctions/arm_fir_lattice_init_q15.d \
./FFT/Source/FilteringFunctions/arm_fir_lattice_init_q31.d \
./FFT/Source/FilteringFunctions/arm_fir_lattice_q15.d \
./FFT/Source/FilteringFunctions/arm_fir_lattice_q31.d \
./FFT/Source/FilteringFunctions/arm_fir_q15.d \
./FFT/Source/FilteringFunctions/arm_fir_q31.d \
./FFT/Source/FilteringFunctions/arm_fir_q7.d \
./FFT/Source/FilteringFunctions/arm_fir_sparse_f32.d \
./FFT/Source/FilteringFunctions/arm_fir_sparse_init_f32.d \
./FFT/Source/FilteringFunctions/arm_fir_sparse_init_q15.d \
./FFT/Source/FilteringFunctions/arm_fir_sparse_init_q31.d \
./FFT/Source/FilteringFunctions/arm_fir_sparse_init_q7.d \
./FFT/Source/FilteringFunctions/arm_fir_sparse_q15.d \
./FFT/Source/FilteringFunctions/arm_fir_sparse_q31.d \
./FFT/Source/FilteringFunctions/arm_fir_sparse_q7.d \
./FFT/Source/FilteringFunctions/arm_iir_lattice_f32.d \
./FFT/Source/FilteringFunctions/arm_iir_lattice_init_f32.d \
./FFT/Source/FilteringFunctions/arm_iir_lattice_init_q15.d \
./FFT/Source/FilteringFunctions/arm_iir_lattice_init_q31.d \
./FFT/Source/FilteringFunctions/arm_iir_lattice_q15.d \
./FFT/Source/FilteringFunctions/arm_iir_lattice_q31.d \
./FFT/Source/FilteringFunctions/arm_levinson_durbin_f16.d \
./FFT/Source/FilteringFunctions/arm_levinson_durbin_f32.d \
./FFT/Source/FilteringFunctions/arm_levinson_durbin_q31.d \
./FFT/Source/FilteringFunctions/arm_lms_f32.d \
./FFT/Source/FilteringFunctions/arm_lms_init_f32.d \
./FFT/Source/FilteringFunctions/arm_lms_init_q15.d \
./FFT/Source/FilteringFunctions/arm_lms_init_q31.d \
./FFT/Source/FilteringFunctions/arm_lms_norm_f32.d \
./FFT/Source/FilteringFunctions/arm_lms_norm_init_f32.d \
./FFT/Source/FilteringFunctions/arm_lms_norm_init_q15.d \
./FFT/Source/FilteringFunctions/arm_lms_norm_init_q31.d \
./FFT/Source/FilteringFunctions/arm_lms_norm_q15.d \
./FFT/Source/FilteringFunctions/arm_lms_norm_q31.d \
./FFT/Source/FilteringFunctions/arm_lms_q15.d \
./FFT/Source/FilteringFunctions/arm_lms_q31.d 


# Each subdirectory must supply rules for building sources it contributes
FFT/Source/FilteringFunctions/%.o FFT/Source/FilteringFunctions/%.su FFT/Source/FilteringFunctions/%.cyclo: ../FFT/Source/FilteringFunctions/%.c FFT/Source/FilteringFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U5A5xx -c -I../../Core/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I"C:/Users/raphael.baumeler/workspace_STM/200_Pinbelegung/STM32CubeIDE/Daten" -I"C:/Users/raphael.baumeler/workspace_STM/200_Pinbelegung/STM32CubeIDE/FFT/Include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-FFT-2f-Source-2f-FilteringFunctions

clean-FFT-2f-Source-2f-FilteringFunctions:
	-$(RM) ./FFT/Source/FilteringFunctions/FilteringFunctions.cyclo ./FFT/Source/FilteringFunctions/FilteringFunctions.d ./FFT/Source/FilteringFunctions/FilteringFunctions.o ./FFT/Source/FilteringFunctions/FilteringFunctions.su ./FFT/Source/FilteringFunctions/FilteringFunctionsF16.cyclo ./FFT/Source/FilteringFunctions/FilteringFunctionsF16.d ./FFT/Source/FilteringFunctions/FilteringFunctionsF16.o ./FFT/Source/FilteringFunctions/FilteringFunctionsF16.su ./FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.cyclo ./FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.d ./FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.o ./FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.su ./FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.cyclo ./FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.d ./FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.o ./FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.su ./FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_f16.cyclo ./FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_f16.d ./FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_f16.o ./FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_f16.su ./FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.cyclo ./FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.d ./FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.o ./FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.su ./FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.cyclo ./FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.d ./FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.o ./FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.su ./FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.cyclo ./FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.d ./FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.o ./FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.su ./FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.cyclo ./FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.d ./FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.o ./FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.su ./FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.cyclo ./FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.d ./FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.o ./FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.su ./FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.cyclo ./FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.d ./FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.o ./FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.su ./FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.cyclo ./FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.d ./FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.o ./FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.su ./FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.cyclo ./FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.d ./FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.o ./FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.su ./FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.cyclo ./FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.d ./FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.o ./FFT/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.su ./FFT/Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.cyclo ./FFT/Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.d ./FFT/Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.o ./FFT/Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.su ./FFT/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.cyclo ./FFT/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.d ./FFT/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.o ./FFT/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.su ./FFT/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.cyclo ./FFT/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.d ./FFT/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.o ./FFT/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.su ./FFT/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.cyclo ./FFT/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.d ./FFT/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.o ./FFT/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.su ./FFT/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.cyclo ./FFT/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.d ./FFT/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.o ./FFT/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.su ./FFT/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.cyclo ./FFT/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.d ./FFT/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.o ./FFT/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.su ./FFT/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.cyclo ./FFT/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.d ./FFT/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.o ./FFT/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.su ./FFT/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.cyclo ./FFT/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.d ./FFT/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.o ./FFT/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.su ./FFT/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.cyclo ./FFT/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.d ./FFT/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.o
	-$(RM) ./FFT/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.su ./FFT/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.cyclo ./FFT/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.d ./FFT/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.o ./FFT/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.su ./FFT/Source/FilteringFunctions/arm_conv_f32.cyclo ./FFT/Source/FilteringFunctions/arm_conv_f32.d ./FFT/Source/FilteringFunctions/arm_conv_f32.o ./FFT/Source/FilteringFunctions/arm_conv_f32.su ./FFT/Source/FilteringFunctions/arm_conv_fast_opt_q15.cyclo ./FFT/Source/FilteringFunctions/arm_conv_fast_opt_q15.d ./FFT/Source/FilteringFunctions/arm_conv_fast_opt_q15.o ./FFT/Source/FilteringFunctions/arm_conv_fast_opt_q15.su ./FFT/Source/FilteringFunctions/arm_conv_fast_q15.cyclo ./FFT/Source/FilteringFunctions/arm_conv_fast_q15.d ./FFT/Source/FilteringFunctions/arm_conv_fast_q15.o ./FFT/Source/FilteringFunctions/arm_conv_fast_q15.su ./FFT/Source/FilteringFunctions/arm_conv_fast_q31.cyclo ./FFT/Source/FilteringFunctions/arm_conv_fast_q31.d ./FFT/Source/FilteringFunctions/arm_conv_fast_q31.o ./FFT/Source/FilteringFunctions/arm_conv_fast_q31.su ./FFT/Source/FilteringFunctions/arm_conv_opt_q15.cyclo ./FFT/Source/FilteringFunctions/arm_conv_opt_q15.d ./FFT/Source/FilteringFunctions/arm_conv_opt_q15.o ./FFT/Source/FilteringFunctions/arm_conv_opt_q15.su ./FFT/Source/FilteringFunctions/arm_conv_opt_q7.cyclo ./FFT/Source/FilteringFunctions/arm_conv_opt_q7.d ./FFT/Source/FilteringFunctions/arm_conv_opt_q7.o ./FFT/Source/FilteringFunctions/arm_conv_opt_q7.su ./FFT/Source/FilteringFunctions/arm_conv_partial_f32.cyclo ./FFT/Source/FilteringFunctions/arm_conv_partial_f32.d ./FFT/Source/FilteringFunctions/arm_conv_partial_f32.o ./FFT/Source/FilteringFunctions/arm_conv_partial_f32.su ./FFT/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.cyclo ./FFT/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.d ./FFT/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.o ./FFT/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.su ./FFT/Source/FilteringFunctions/arm_conv_partial_fast_q15.cyclo ./FFT/Source/FilteringFunctions/arm_conv_partial_fast_q15.d ./FFT/Source/FilteringFunctions/arm_conv_partial_fast_q15.o ./FFT/Source/FilteringFunctions/arm_conv_partial_fast_q15.su ./FFT/Source/FilteringFunctions/arm_conv_partial_fast_q31.cyclo ./FFT/Source/FilteringFunctions/arm_conv_partial_fast_q31.d ./FFT/Source/FilteringFunctions/arm_conv_partial_fast_q31.o ./FFT/Source/FilteringFunctions/arm_conv_partial_fast_q31.su ./FFT/Source/FilteringFunctions/arm_conv_partial_opt_q15.cyclo ./FFT/Source/FilteringFunctions/arm_conv_partial_opt_q15.d ./FFT/Source/FilteringFunctions/arm_conv_partial_opt_q15.o ./FFT/Source/FilteringFunctions/arm_conv_partial_opt_q15.su ./FFT/Source/FilteringFunctions/arm_conv_partial_opt_q7.cyclo ./FFT/Source/FilteringFunctions/arm_conv_partial_opt_q7.d ./FFT/Source/FilteringFunctions/arm_conv_partial_opt_q7.o ./FFT/Source/FilteringFunctions/arm_conv_partial_opt_q7.su ./FFT/Source/FilteringFunctions/arm_conv_partial_q15.cyclo ./FFT/Source/FilteringFunctions/arm_conv_partial_q15.d ./FFT/Source/FilteringFunctions/arm_conv_partial_q15.o ./FFT/Source/FilteringFunctions/arm_conv_partial_q15.su ./FFT/Source/FilteringFunctions/arm_conv_partial_q31.cyclo ./FFT/Source/FilteringFunctions/arm_conv_partial_q31.d ./FFT/Source/FilteringFunctions/arm_conv_partial_q31.o ./FFT/Source/FilteringFunctions/arm_conv_partial_q31.su ./FFT/Source/FilteringFunctions/arm_conv_partial_q7.cyclo ./FFT/Source/FilteringFunctions/arm_conv_partial_q7.d ./FFT/Source/FilteringFunctions/arm_conv_partial_q7.o ./FFT/Source/FilteringFunctions/arm_conv_partial_q7.su ./FFT/Source/FilteringFunctions/arm_conv_q15.cyclo ./FFT/Source/FilteringFunctions/arm_conv_q15.d ./FFT/Source/FilteringFunctions/arm_conv_q15.o ./FFT/Source/FilteringFunctions/arm_conv_q15.su ./FFT/Source/FilteringFunctions/arm_conv_q31.cyclo ./FFT/Source/FilteringFunctions/arm_conv_q31.d ./FFT/Source/FilteringFunctions/arm_conv_q31.o ./FFT/Source/FilteringFunctions/arm_conv_q31.su ./FFT/Source/FilteringFunctions/arm_conv_q7.cyclo ./FFT/Source/FilteringFunctions/arm_conv_q7.d ./FFT/Source/FilteringFunctions/arm_conv_q7.o ./FFT/Source/FilteringFunctions/arm_conv_q7.su ./FFT/Source/FilteringFunctions/arm_correlate_f16.cyclo ./FFT/Source/FilteringFunctions/arm_correlate_f16.d ./FFT/Source/FilteringFunctions/arm_correlate_f16.o ./FFT/Source/FilteringFunctions/arm_correlate_f16.su ./FFT/Source/FilteringFunctions/arm_correlate_f32.cyclo ./FFT/Source/FilteringFunctions/arm_correlate_f32.d ./FFT/Source/FilteringFunctions/arm_correlate_f32.o ./FFT/Source/FilteringFunctions/arm_correlate_f32.su ./FFT/Source/FilteringFunctions/arm_correlate_f64.cyclo ./FFT/Source/FilteringFunctions/arm_correlate_f64.d ./FFT/Source/FilteringFunctions/arm_correlate_f64.o ./FFT/Source/FilteringFunctions/arm_correlate_f64.su ./FFT/Source/FilteringFunctions/arm_correlate_fast_opt_q15.cyclo ./FFT/Source/FilteringFunctions/arm_correlate_fast_opt_q15.d ./FFT/Source/FilteringFunctions/arm_correlate_fast_opt_q15.o ./FFT/Source/FilteringFunctions/arm_correlate_fast_opt_q15.su ./FFT/Source/FilteringFunctions/arm_correlate_fast_q15.cyclo ./FFT/Source/FilteringFunctions/arm_correlate_fast_q15.d ./FFT/Source/FilteringFunctions/arm_correlate_fast_q15.o ./FFT/Source/FilteringFunctions/arm_correlate_fast_q15.su ./FFT/Source/FilteringFunctions/arm_correlate_fast_q31.cyclo ./FFT/Source/FilteringFunctions/arm_correlate_fast_q31.d ./FFT/Source/FilteringFunctions/arm_correlate_fast_q31.o ./FFT/Source/FilteringFunctions/arm_correlate_fast_q31.su ./FFT/Source/FilteringFunctions/arm_correlate_opt_q15.cyclo ./FFT/Source/FilteringFunctions/arm_correlate_opt_q15.d ./FFT/Source/FilteringFunctions/arm_correlate_opt_q15.o ./FFT/Source/FilteringFunctions/arm_correlate_opt_q15.su ./FFT/Source/FilteringFunctions/arm_correlate_opt_q7.cyclo
	-$(RM) ./FFT/Source/FilteringFunctions/arm_correlate_opt_q7.d ./FFT/Source/FilteringFunctions/arm_correlate_opt_q7.o ./FFT/Source/FilteringFunctions/arm_correlate_opt_q7.su ./FFT/Source/FilteringFunctions/arm_correlate_q15.cyclo ./FFT/Source/FilteringFunctions/arm_correlate_q15.d ./FFT/Source/FilteringFunctions/arm_correlate_q15.o ./FFT/Source/FilteringFunctions/arm_correlate_q15.su ./FFT/Source/FilteringFunctions/arm_correlate_q31.cyclo ./FFT/Source/FilteringFunctions/arm_correlate_q31.d ./FFT/Source/FilteringFunctions/arm_correlate_q31.o ./FFT/Source/FilteringFunctions/arm_correlate_q31.su ./FFT/Source/FilteringFunctions/arm_correlate_q7.cyclo ./FFT/Source/FilteringFunctions/arm_correlate_q7.d ./FFT/Source/FilteringFunctions/arm_correlate_q7.o ./FFT/Source/FilteringFunctions/arm_correlate_q7.su ./FFT/Source/FilteringFunctions/arm_fir_decimate_f32.cyclo ./FFT/Source/FilteringFunctions/arm_fir_decimate_f32.d ./FFT/Source/FilteringFunctions/arm_fir_decimate_f32.o ./FFT/Source/FilteringFunctions/arm_fir_decimate_f32.su ./FFT/Source/FilteringFunctions/arm_fir_decimate_f64.cyclo ./FFT/Source/FilteringFunctions/arm_fir_decimate_f64.d ./FFT/Source/FilteringFunctions/arm_fir_decimate_f64.o ./FFT/Source/FilteringFunctions/arm_fir_decimate_f64.su ./FFT/Source/FilteringFunctions/arm_fir_decimate_fast_q15.cyclo ./FFT/Source/FilteringFunctions/arm_fir_decimate_fast_q15.d ./FFT/Source/FilteringFunctions/arm_fir_decimate_fast_q15.o ./FFT/Source/FilteringFunctions/arm_fir_decimate_fast_q15.su ./FFT/Source/FilteringFunctions/arm_fir_decimate_fast_q31.cyclo ./FFT/Source/FilteringFunctions/arm_fir_decimate_fast_q31.d ./FFT/Source/FilteringFunctions/arm_fir_decimate_fast_q31.o ./FFT/Source/FilteringFunctions/arm_fir_decimate_fast_q31.su ./FFT/Source/FilteringFunctions/arm_fir_decimate_init_f32.cyclo ./FFT/Source/FilteringFunctions/arm_fir_decimate_init_f32.d ./FFT/Source/FilteringFunctions/arm_fir_decimate_init_f32.o ./FFT/Source/FilteringFunctions/arm_fir_decimate_init_f32.su ./FFT/Source/FilteringFunctions/arm_fir_decimate_init_f64.cyclo ./FFT/Source/FilteringFunctions/arm_fir_decimate_init_f64.d ./FFT/Source/FilteringFunctions/arm_fir_decimate_init_f64.o ./FFT/Source/FilteringFunctions/arm_fir_decimate_init_f64.su ./FFT/Source/FilteringFunctions/arm_fir_decimate_init_q15.cyclo ./FFT/Source/FilteringFunctions/arm_fir_decimate_init_q15.d ./FFT/Source/FilteringFunctions/arm_fir_decimate_init_q15.o ./FFT/Source/FilteringFunctions/arm_fir_decimate_init_q15.su ./FFT/Source/FilteringFunctions/arm_fir_decimate_init_q31.cyclo ./FFT/Source/FilteringFunctions/arm_fir_decimate_init_q31.d ./FFT/Source/FilteringFunctions/arm_fir_decimate_init_q31.o ./FFT/Source/FilteringFunctions/arm_fir_decimate_init_q31.su ./FFT/Source/FilteringFunctions/arm_fir_decimate_q15.cyclo ./FFT/Source/FilteringFunctions/arm_fir_decimate_q15.d ./FFT/Source/FilteringFunctions/arm_fir_decimate_q15.o ./FFT/Source/FilteringFunctions/arm_fir_decimate_q15.su ./FFT/Source/FilteringFunctions/arm_fir_decimate_q31.cyclo ./FFT/Source/FilteringFunctions/arm_fir_decimate_q31.d ./FFT/Source/FilteringFunctions/arm_fir_decimate_q31.o ./FFT/Source/FilteringFunctions/arm_fir_decimate_q31.su ./FFT/Source/FilteringFunctions/arm_fir_f16.cyclo ./FFT/Source/FilteringFunctions/arm_fir_f16.d ./FFT/Source/FilteringFunctions/arm_fir_f16.o ./FFT/Source/FilteringFunctions/arm_fir_f16.su ./FFT/Source/FilteringFunctions/arm_fir_f32.cyclo ./FFT/Source/FilteringFunctions/arm_fir_f32.d ./FFT/Source/FilteringFunctions/arm_fir_f32.o ./FFT/Source/FilteringFunctions/arm_fir_f32.su ./FFT/Source/FilteringFunctions/arm_fir_f64.cyclo ./FFT/Source/FilteringFunctions/arm_fir_f64.d ./FFT/Source/FilteringFunctions/arm_fir_f64.o ./FFT/Source/FilteringFunctions/arm_fir_f64.su ./FFT/Source/FilteringFunctions/arm_fir_fast_q15.cyclo ./FFT/Source/FilteringFunctions/arm_fir_fast_q15.d ./FFT/Source/FilteringFunctions/arm_fir_fast_q15.o ./FFT/Source/FilteringFunctions/arm_fir_fast_q15.su ./FFT/Source/FilteringFunctions/arm_fir_fast_q31.cyclo ./FFT/Source/FilteringFunctions/arm_fir_fast_q31.d ./FFT/Source/FilteringFunctions/arm_fir_fast_q31.o ./FFT/Source/FilteringFunctions/arm_fir_fast_q31.su ./FFT/Source/FilteringFunctions/arm_fir_init_f16.cyclo ./FFT/Source/FilteringFunctions/arm_fir_init_f16.d ./FFT/Source/FilteringFunctions/arm_fir_init_f16.o ./FFT/Source/FilteringFunctions/arm_fir_init_f16.su ./FFT/Source/FilteringFunctions/arm_fir_init_f32.cyclo ./FFT/Source/FilteringFunctions/arm_fir_init_f32.d ./FFT/Source/FilteringFunctions/arm_fir_init_f32.o ./FFT/Source/FilteringFunctions/arm_fir_init_f32.su ./FFT/Source/FilteringFunctions/arm_fir_init_f64.cyclo ./FFT/Source/FilteringFunctions/arm_fir_init_f64.d ./FFT/Source/FilteringFunctions/arm_fir_init_f64.o ./FFT/Source/FilteringFunctions/arm_fir_init_f64.su ./FFT/Source/FilteringFunctions/arm_fir_init_q15.cyclo ./FFT/Source/FilteringFunctions/arm_fir_init_q15.d ./FFT/Source/FilteringFunctions/arm_fir_init_q15.o ./FFT/Source/FilteringFunctions/arm_fir_init_q15.su ./FFT/Source/FilteringFunctions/arm_fir_init_q31.cyclo ./FFT/Source/FilteringFunctions/arm_fir_init_q31.d ./FFT/Source/FilteringFunctions/arm_fir_init_q31.o ./FFT/Source/FilteringFunctions/arm_fir_init_q31.su ./FFT/Source/FilteringFunctions/arm_fir_init_q7.cyclo ./FFT/Source/FilteringFunctions/arm_fir_init_q7.d ./FFT/Source/FilteringFunctions/arm_fir_init_q7.o ./FFT/Source/FilteringFunctions/arm_fir_init_q7.su ./FFT/Source/FilteringFunctions/arm_fir_interpolate_f32.cyclo ./FFT/Source/FilteringFunctions/arm_fir_interpolate_f32.d ./FFT/Source/FilteringFunctions/arm_fir_interpolate_f32.o ./FFT/Source/FilteringFunctions/arm_fir_interpolate_f32.su ./FFT/Source/FilteringFunctions/arm_fir_interpolate_init_f32.cyclo ./FFT/Source/FilteringFunctions/arm_fir_interpolate_init_f32.d ./FFT/Source/FilteringFunctions/arm_fir_interpolate_init_f32.o ./FFT/Source/FilteringFunctions/arm_fir_interpolate_init_f32.su ./FFT/Source/FilteringFunctions/arm_fir_interpolate_init_q15.cyclo
	-$(RM) ./FFT/Source/FilteringFunctions/arm_fir_interpolate_init_q15.d ./FFT/Source/FilteringFunctions/arm_fir_interpolate_init_q15.o ./FFT/Source/FilteringFunctions/arm_fir_interpolate_init_q15.su ./FFT/Source/FilteringFunctions/arm_fir_interpolate_init_q31.cyclo ./FFT/Source/FilteringFunctions/arm_fir_interpolate_init_q31.d ./FFT/Source/FilteringFunctions/arm_fir_interpolate_init_q31.o ./FFT/Source/FilteringFunctions/arm_fir_interpolate_init_q31.su ./FFT/Source/FilteringFunctions/arm_fir_interpolate_q15.cyclo ./FFT/Source/FilteringFunctions/arm_fir_interpolate_q15.d ./FFT/Source/FilteringFunctions/arm_fir_interpolate_q15.o ./FFT/Source/FilteringFunctions/arm_fir_interpolate_q15.su ./FFT/Source/FilteringFunctions/arm_fir_interpolate_q31.cyclo ./FFT/Source/FilteringFunctions/arm_fir_interpolate_q31.d ./FFT/Source/FilteringFunctions/arm_fir_interpolate_q31.o ./FFT/Source/FilteringFunctions/arm_fir_interpolate_q31.su ./FFT/Source/FilteringFunctions/arm_fir_lattice_f32.cyclo ./FFT/Source/FilteringFunctions/arm_fir_lattice_f32.d ./FFT/Source/FilteringFunctions/arm_fir_lattice_f32.o ./FFT/Source/FilteringFunctions/arm_fir_lattice_f32.su ./FFT/Source/FilteringFunctions/arm_fir_lattice_init_f32.cyclo ./FFT/Source/FilteringFunctions/arm_fir_lattice_init_f32.d ./FFT/Source/FilteringFunctions/arm_fir_lattice_init_f32.o ./FFT/Source/FilteringFunctions/arm_fir_lattice_init_f32.su ./FFT/Source/FilteringFunctions/arm_fir_lattice_init_q15.cyclo ./FFT/Source/FilteringFunctions/arm_fir_lattice_init_q15.d ./FFT/Source/FilteringFunctions/arm_fir_lattice_init_q15.o ./FFT/Source/FilteringFunctions/arm_fir_lattice_init_q15.su ./FFT/Source/FilteringFunctions/arm_fir_lattice_init_q31.cyclo ./FFT/Source/FilteringFunctions/arm_fir_lattice_init_q31.d ./FFT/Source/FilteringFunctions/arm_fir_lattice_init_q31.o ./FFT/Source/FilteringFunctions/arm_fir_lattice_init_q31.su ./FFT/Source/FilteringFunctions/arm_fir_lattice_q15.cyclo ./FFT/Source/FilteringFunctions/arm_fir_lattice_q15.d ./FFT/Source/FilteringFunctions/arm_fir_lattice_q15.o ./FFT/Source/FilteringFunctions/arm_fir_lattice_q15.su ./FFT/Source/FilteringFunctions/arm_fir_lattice_q31.cyclo ./FFT/Source/FilteringFunctions/arm_fir_lattice_q31.d ./FFT/Source/FilteringFunctions/arm_fir_lattice_q31.o ./FFT/Source/FilteringFunctions/arm_fir_lattice_q31.su ./FFT/Source/FilteringFunctions/arm_fir_q15.cyclo ./FFT/Source/FilteringFunctions/arm_fir_q15.d ./FFT/Source/FilteringFunctions/arm_fir_q15.o ./FFT/Source/FilteringFunctions/arm_fir_q15.su ./FFT/Source/FilteringFunctions/arm_fir_q31.cyclo ./FFT/Source/FilteringFunctions/arm_fir_q31.d ./FFT/Source/FilteringFunctions/arm_fir_q31.o ./FFT/Source/FilteringFunctions/arm_fir_q31.su ./FFT/Source/FilteringFunctions/arm_fir_q7.cyclo ./FFT/Source/FilteringFunctions/arm_fir_q7.d ./FFT/Source/FilteringFunctions/arm_fir_q7.o ./FFT/Source/FilteringFunctions/arm_fir_q7.su ./FFT/Source/FilteringFunctions/arm_fir_sparse_f32.cyclo ./FFT/Source/FilteringFunctions/arm_fir_sparse_f32.d ./FFT/Source/FilteringFunctions/arm_fir_sparse_f32.o ./FFT/Source/FilteringFunctions/arm_fir_sparse_f32.su ./FFT/Source/FilteringFunctions/arm_fir_sparse_init_f32.cyclo ./FFT/Source/FilteringFunctions/arm_fir_sparse_init_f32.d ./FFT/Source/FilteringFunctions/arm_fir_sparse_init_f32.o ./FFT/Source/FilteringFunctions/arm_fir_sparse_init_f32.su ./FFT/Source/FilteringFunctions/arm_fir_sparse_init_q15.cyclo ./FFT/Source/FilteringFunctions/arm_fir_sparse_init_q15.d ./FFT/Source/FilteringFunctions/arm_fir_sparse_init_q15.o ./FFT/Source/FilteringFunctions/arm_fir_sparse_init_q15.su ./FFT/Source/FilteringFunctions/arm_fir_sparse_init_q31.cyclo ./FFT/Source/FilteringFunctions/arm_fir_sparse_init_q31.d ./FFT/Source/FilteringFunctions/arm_fir_sparse_init_q31.o ./FFT/Source/FilteringFunctions/arm_fir_sparse_init_q31.su ./FFT/Source/FilteringFunctions/arm_fir_sparse_init_q7.cyclo ./FFT/Source/FilteringFunctions/arm_fir_sparse_init_q7.d ./FFT/Source/FilteringFunctions/arm_fir_sparse_init_q7.o ./FFT/Source/FilteringFunctions/arm_fir_sparse_init_q7.su ./FFT/Source/FilteringFunctions/arm_fir_sparse_q15.cyclo ./FFT/Source/FilteringFunctions/arm_fir_sparse_q15.d ./FFT/Source/FilteringFunctions/arm_fir_sparse_q15.o ./FFT/Source/FilteringFunctions/arm_fir_sparse_q15.su ./FFT/Source/FilteringFunctions/arm_fir_sparse_q31.cyclo ./FFT/Source/FilteringFunctions/arm_fir_sparse_q31.d ./FFT/Source/FilteringFunctions/arm_fir_sparse_q31.o ./FFT/Source/FilteringFunctions/arm_fir_sparse_q31.su ./FFT/Source/FilteringFunctions/arm_fir_sparse_q7.cyclo ./FFT/Source/FilteringFunctions/arm_fir_sparse_q7.d ./FFT/Source/FilteringFunctions/arm_fir_sparse_q7.o ./FFT/Source/FilteringFunctions/arm_fir_sparse_q7.su ./FFT/Source/FilteringFunctions/arm_iir_lattice_f32.cyclo ./FFT/Source/FilteringFunctions/arm_iir_lattice_f32.d ./FFT/Source/FilteringFunctions/arm_iir_lattice_f32.o ./FFT/Source/FilteringFunctions/arm_iir_lattice_f32.su ./FFT/Source/FilteringFunctions/arm_iir_lattice_init_f32.cyclo ./FFT/Source/FilteringFunctions/arm_iir_lattice_init_f32.d ./FFT/Source/FilteringFunctions/arm_iir_lattice_init_f32.o ./FFT/Source/FilteringFunctions/arm_iir_lattice_init_f32.su ./FFT/Source/FilteringFunctions/arm_iir_lattice_init_q15.cyclo ./FFT/Source/FilteringFunctions/arm_iir_lattice_init_q15.d ./FFT/Source/FilteringFunctions/arm_iir_lattice_init_q15.o ./FFT/Source/FilteringFunctions/arm_iir_lattice_init_q15.su ./FFT/Source/FilteringFunctions/arm_iir_lattice_init_q31.cyclo ./FFT/Source/FilteringFunctions/arm_iir_lattice_init_q31.d ./FFT/Source/FilteringFunctions/arm_iir_lattice_init_q31.o ./FFT/Source/FilteringFunctions/arm_iir_lattice_init_q31.su ./FFT/Source/FilteringFunctions/arm_iir_lattice_q15.cyclo ./FFT/Source/FilteringFunctions/arm_iir_lattice_q15.d ./FFT/Source/FilteringFunctions/arm_iir_lattice_q15.o ./FFT/Source/FilteringFunctions/arm_iir_lattice_q15.su ./FFT/Source/FilteringFunctions/arm_iir_lattice_q31.cyclo ./FFT/Source/FilteringFunctions/arm_iir_lattice_q31.d
	-$(RM) ./FFT/Source/FilteringFunctions/arm_iir_lattice_q31.o ./FFT/Source/FilteringFunctions/arm_iir_lattice_q31.su ./FFT/Source/FilteringFunctions/arm_levinson_durbin_f16.cyclo ./FFT/Source/FilteringFunctions/arm_levinson_durbin_f16.d ./FFT/Source/FilteringFunctions/arm_levinson_durbin_f16.o ./FFT/Source/FilteringFunctions/arm_levinson_durbin_f16.su ./FFT/Source/FilteringFunctions/arm_levinson_durbin_f32.cyclo ./FFT/Source/FilteringFunctions/arm_levinson_durbin_f32.d ./FFT/Source/FilteringFunctions/arm_levinson_durbin_f32.o ./FFT/Source/FilteringFunctions/arm_levinson_durbin_f32.su ./FFT/Source/FilteringFunctions/arm_levinson_durbin_q31.cyclo ./FFT/Source/FilteringFunctions/arm_levinson_durbin_q31.d ./FFT/Source/FilteringFunctions/arm_levinson_durbin_q31.o ./FFT/Source/FilteringFunctions/arm_levinson_durbin_q31.su ./FFT/Source/FilteringFunctions/arm_lms_f32.cyclo ./FFT/Source/FilteringFunctions/arm_lms_f32.d ./FFT/Source/FilteringFunctions/arm_lms_f32.o ./FFT/Source/FilteringFunctions/arm_lms_f32.su ./FFT/Source/FilteringFunctions/arm_lms_init_f32.cyclo ./FFT/Source/FilteringFunctions/arm_lms_init_f32.d ./FFT/Source/FilteringFunctions/arm_lms_init_f32.o ./FFT/Source/FilteringFunctions/arm_lms_init_f32.su ./FFT/Source/FilteringFunctions/arm_lms_init_q15.cyclo ./FFT/Source/FilteringFunctions/arm_lms_init_q15.d ./FFT/Source/FilteringFunctions/arm_lms_init_q15.o ./FFT/Source/FilteringFunctions/arm_lms_init_q15.su ./FFT/Source/FilteringFunctions/arm_lms_init_q31.cyclo ./FFT/Source/FilteringFunctions/arm_lms_init_q31.d ./FFT/Source/FilteringFunctions/arm_lms_init_q31.o ./FFT/Source/FilteringFunctions/arm_lms_init_q31.su ./FFT/Source/FilteringFunctions/arm_lms_norm_f32.cyclo ./FFT/Source/FilteringFunctions/arm_lms_norm_f32.d ./FFT/Source/FilteringFunctions/arm_lms_norm_f32.o ./FFT/Source/FilteringFunctions/arm_lms_norm_f32.su ./FFT/Source/FilteringFunctions/arm_lms_norm_init_f32.cyclo ./FFT/Source/FilteringFunctions/arm_lms_norm_init_f32.d ./FFT/Source/FilteringFunctions/arm_lms_norm_init_f32.o ./FFT/Source/FilteringFunctions/arm_lms_norm_init_f32.su ./FFT/Source/FilteringFunctions/arm_lms_norm_init_q15.cyclo ./FFT/Source/FilteringFunctions/arm_lms_norm_init_q15.d ./FFT/Source/FilteringFunctions/arm_lms_norm_init_q15.o ./FFT/Source/FilteringFunctions/arm_lms_norm_init_q15.su ./FFT/Source/FilteringFunctions/arm_lms_norm_init_q31.cyclo ./FFT/Source/FilteringFunctions/arm_lms_norm_init_q31.d ./FFT/Source/FilteringFunctions/arm_lms_norm_init_q31.o ./FFT/Source/FilteringFunctions/arm_lms_norm_init_q31.su ./FFT/Source/FilteringFunctions/arm_lms_norm_q15.cyclo ./FFT/Source/FilteringFunctions/arm_lms_norm_q15.d ./FFT/Source/FilteringFunctions/arm_lms_norm_q15.o ./FFT/Source/FilteringFunctions/arm_lms_norm_q15.su ./FFT/Source/FilteringFunctions/arm_lms_norm_q31.cyclo ./FFT/Source/FilteringFunctions/arm_lms_norm_q31.d ./FFT/Source/FilteringFunctions/arm_lms_norm_q31.o ./FFT/Source/FilteringFunctions/arm_lms_norm_q31.su ./FFT/Source/FilteringFunctions/arm_lms_q15.cyclo ./FFT/Source/FilteringFunctions/arm_lms_q15.d ./FFT/Source/FilteringFunctions/arm_lms_q15.o ./FFT/Source/FilteringFunctions/arm_lms_q15.su ./FFT/Source/FilteringFunctions/arm_lms_q31.cyclo ./FFT/Source/FilteringFunctions/arm_lms_q31.d ./FFT/Source/FilteringFunctions/arm_lms_q31.o ./FFT/Source/FilteringFunctions/arm_lms_q31.su

.PHONY: clean-FFT-2f-Source-2f-FilteringFunctions

