################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (14.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../FFT/Source/StatisticsFunctions/StatisticsFunctions.c \
../FFT/Source/StatisticsFunctions/StatisticsFunctionsF16.c \
../FFT/Source/StatisticsFunctions/arm_absmax_f16.c \
../FFT/Source/StatisticsFunctions/arm_absmax_f32.c \
../FFT/Source/StatisticsFunctions/arm_absmax_f64.c \
../FFT/Source/StatisticsFunctions/arm_absmax_no_idx_f16.c \
../FFT/Source/StatisticsFunctions/arm_absmax_no_idx_f32.c \
../FFT/Source/StatisticsFunctions/arm_absmax_no_idx_f64.c \
../FFT/Source/StatisticsFunctions/arm_absmax_no_idx_q15.c \
../FFT/Source/StatisticsFunctions/arm_absmax_no_idx_q31.c \
../FFT/Source/StatisticsFunctions/arm_absmax_no_idx_q7.c \
../FFT/Source/StatisticsFunctions/arm_absmax_q15.c \
../FFT/Source/StatisticsFunctions/arm_absmax_q31.c \
../FFT/Source/StatisticsFunctions/arm_absmax_q7.c \
../FFT/Source/StatisticsFunctions/arm_absmin_f16.c \
../FFT/Source/StatisticsFunctions/arm_absmin_f32.c \
../FFT/Source/StatisticsFunctions/arm_absmin_f64.c \
../FFT/Source/StatisticsFunctions/arm_absmin_no_idx_f16.c \
../FFT/Source/StatisticsFunctions/arm_absmin_no_idx_f32.c \
../FFT/Source/StatisticsFunctions/arm_absmin_no_idx_f64.c \
../FFT/Source/StatisticsFunctions/arm_absmin_no_idx_q15.c \
../FFT/Source/StatisticsFunctions/arm_absmin_no_idx_q31.c \
../FFT/Source/StatisticsFunctions/arm_absmin_no_idx_q7.c \
../FFT/Source/StatisticsFunctions/arm_absmin_q15.c \
../FFT/Source/StatisticsFunctions/arm_absmin_q31.c \
../FFT/Source/StatisticsFunctions/arm_absmin_q7.c \
../FFT/Source/StatisticsFunctions/arm_accumulate_f16.c \
../FFT/Source/StatisticsFunctions/arm_accumulate_f32.c \
../FFT/Source/StatisticsFunctions/arm_accumulate_f64.c \
../FFT/Source/StatisticsFunctions/arm_entropy_f16.c \
../FFT/Source/StatisticsFunctions/arm_entropy_f32.c \
../FFT/Source/StatisticsFunctions/arm_entropy_f64.c \
../FFT/Source/StatisticsFunctions/arm_kullback_leibler_f16.c \
../FFT/Source/StatisticsFunctions/arm_kullback_leibler_f32.c \
../FFT/Source/StatisticsFunctions/arm_kullback_leibler_f64.c \
../FFT/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.c \
../FFT/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.c \
../FFT/Source/StatisticsFunctions/arm_logsumexp_f16.c \
../FFT/Source/StatisticsFunctions/arm_logsumexp_f32.c \
../FFT/Source/StatisticsFunctions/arm_max_f16.c \
../FFT/Source/StatisticsFunctions/arm_max_f32.c \
../FFT/Source/StatisticsFunctions/arm_max_f64.c \
../FFT/Source/StatisticsFunctions/arm_max_no_idx_f16.c \
../FFT/Source/StatisticsFunctions/arm_max_no_idx_f32.c \
../FFT/Source/StatisticsFunctions/arm_max_no_idx_f64.c \
../FFT/Source/StatisticsFunctions/arm_max_no_idx_q15.c \
../FFT/Source/StatisticsFunctions/arm_max_no_idx_q31.c \
../FFT/Source/StatisticsFunctions/arm_max_no_idx_q7.c \
../FFT/Source/StatisticsFunctions/arm_max_q15.c \
../FFT/Source/StatisticsFunctions/arm_max_q31.c \
../FFT/Source/StatisticsFunctions/arm_max_q7.c \
../FFT/Source/StatisticsFunctions/arm_mean_f16.c \
../FFT/Source/StatisticsFunctions/arm_mean_f32.c \
../FFT/Source/StatisticsFunctions/arm_mean_f64.c \
../FFT/Source/StatisticsFunctions/arm_mean_q15.c \
../FFT/Source/StatisticsFunctions/arm_mean_q31.c \
../FFT/Source/StatisticsFunctions/arm_mean_q7.c \
../FFT/Source/StatisticsFunctions/arm_min_f16.c \
../FFT/Source/StatisticsFunctions/arm_min_f32.c \
../FFT/Source/StatisticsFunctions/arm_min_f64.c \
../FFT/Source/StatisticsFunctions/arm_min_no_idx_f16.c \
../FFT/Source/StatisticsFunctions/arm_min_no_idx_f32.c \
../FFT/Source/StatisticsFunctions/arm_min_no_idx_f64.c \
../FFT/Source/StatisticsFunctions/arm_min_no_idx_q15.c \
../FFT/Source/StatisticsFunctions/arm_min_no_idx_q31.c \
../FFT/Source/StatisticsFunctions/arm_min_no_idx_q7.c \
../FFT/Source/StatisticsFunctions/arm_min_q15.c \
../FFT/Source/StatisticsFunctions/arm_min_q31.c \
../FFT/Source/StatisticsFunctions/arm_min_q7.c \
../FFT/Source/StatisticsFunctions/arm_mse_f16.c \
../FFT/Source/StatisticsFunctions/arm_mse_f32.c \
../FFT/Source/StatisticsFunctions/arm_mse_f64.c \
../FFT/Source/StatisticsFunctions/arm_mse_q15.c \
../FFT/Source/StatisticsFunctions/arm_mse_q31.c \
../FFT/Source/StatisticsFunctions/arm_mse_q7.c \
../FFT/Source/StatisticsFunctions/arm_power_f16.c \
../FFT/Source/StatisticsFunctions/arm_power_f32.c \
../FFT/Source/StatisticsFunctions/arm_power_f64.c \
../FFT/Source/StatisticsFunctions/arm_power_q15.c \
../FFT/Source/StatisticsFunctions/arm_power_q31.c \
../FFT/Source/StatisticsFunctions/arm_power_q7.c \
../FFT/Source/StatisticsFunctions/arm_rms_f16.c \
../FFT/Source/StatisticsFunctions/arm_rms_f32.c \
../FFT/Source/StatisticsFunctions/arm_rms_q15.c \
../FFT/Source/StatisticsFunctions/arm_rms_q31.c \
../FFT/Source/StatisticsFunctions/arm_std_f16.c \
../FFT/Source/StatisticsFunctions/arm_std_f32.c \
../FFT/Source/StatisticsFunctions/arm_std_f64.c \
../FFT/Source/StatisticsFunctions/arm_std_q15.c \
../FFT/Source/StatisticsFunctions/arm_std_q31.c \
../FFT/Source/StatisticsFunctions/arm_var_f16.c \
../FFT/Source/StatisticsFunctions/arm_var_f32.c \
../FFT/Source/StatisticsFunctions/arm_var_f64.c \
../FFT/Source/StatisticsFunctions/arm_var_q15.c \
../FFT/Source/StatisticsFunctions/arm_var_q31.c 

OBJS += \
./FFT/Source/StatisticsFunctions/StatisticsFunctions.o \
./FFT/Source/StatisticsFunctions/StatisticsFunctionsF16.o \
./FFT/Source/StatisticsFunctions/arm_absmax_f16.o \
./FFT/Source/StatisticsFunctions/arm_absmax_f32.o \
./FFT/Source/StatisticsFunctions/arm_absmax_f64.o \
./FFT/Source/StatisticsFunctions/arm_absmax_no_idx_f16.o \
./FFT/Source/StatisticsFunctions/arm_absmax_no_idx_f32.o \
./FFT/Source/StatisticsFunctions/arm_absmax_no_idx_f64.o \
./FFT/Source/StatisticsFunctions/arm_absmax_no_idx_q15.o \
./FFT/Source/StatisticsFunctions/arm_absmax_no_idx_q31.o \
./FFT/Source/StatisticsFunctions/arm_absmax_no_idx_q7.o \
./FFT/Source/StatisticsFunctions/arm_absmax_q15.o \
./FFT/Source/StatisticsFunctions/arm_absmax_q31.o \
./FFT/Source/StatisticsFunctions/arm_absmax_q7.o \
./FFT/Source/StatisticsFunctions/arm_absmin_f16.o \
./FFT/Source/StatisticsFunctions/arm_absmin_f32.o \
./FFT/Source/StatisticsFunctions/arm_absmin_f64.o \
./FFT/Source/StatisticsFunctions/arm_absmin_no_idx_f16.o \
./FFT/Source/StatisticsFunctions/arm_absmin_no_idx_f32.o \
./FFT/Source/StatisticsFunctions/arm_absmin_no_idx_f64.o \
./FFT/Source/StatisticsFunctions/arm_absmin_no_idx_q15.o \
./FFT/Source/StatisticsFunctions/arm_absmin_no_idx_q31.o \
./FFT/Source/StatisticsFunctions/arm_absmin_no_idx_q7.o \
./FFT/Source/StatisticsFunctions/arm_absmin_q15.o \
./FFT/Source/StatisticsFunctions/arm_absmin_q31.o \
./FFT/Source/StatisticsFunctions/arm_absmin_q7.o \
./FFT/Source/StatisticsFunctions/arm_accumulate_f16.o \
./FFT/Source/StatisticsFunctions/arm_accumulate_f32.o \
./FFT/Source/StatisticsFunctions/arm_accumulate_f64.o \
./FFT/Source/StatisticsFunctions/arm_entropy_f16.o \
./FFT/Source/StatisticsFunctions/arm_entropy_f32.o \
./FFT/Source/StatisticsFunctions/arm_entropy_f64.o \
./FFT/Source/StatisticsFunctions/arm_kullback_leibler_f16.o \
./FFT/Source/StatisticsFunctions/arm_kullback_leibler_f32.o \
./FFT/Source/StatisticsFunctions/arm_kullback_leibler_f64.o \
./FFT/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.o \
./FFT/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.o \
./FFT/Source/StatisticsFunctions/arm_logsumexp_f16.o \
./FFT/Source/StatisticsFunctions/arm_logsumexp_f32.o \
./FFT/Source/StatisticsFunctions/arm_max_f16.o \
./FFT/Source/StatisticsFunctions/arm_max_f32.o \
./FFT/Source/StatisticsFunctions/arm_max_f64.o \
./FFT/Source/StatisticsFunctions/arm_max_no_idx_f16.o \
./FFT/Source/StatisticsFunctions/arm_max_no_idx_f32.o \
./FFT/Source/StatisticsFunctions/arm_max_no_idx_f64.o \
./FFT/Source/StatisticsFunctions/arm_max_no_idx_q15.o \
./FFT/Source/StatisticsFunctions/arm_max_no_idx_q31.o \
./FFT/Source/StatisticsFunctions/arm_max_no_idx_q7.o \
./FFT/Source/StatisticsFunctions/arm_max_q15.o \
./FFT/Source/StatisticsFunctions/arm_max_q31.o \
./FFT/Source/StatisticsFunctions/arm_max_q7.o \
./FFT/Source/StatisticsFunctions/arm_mean_f16.o \
./FFT/Source/StatisticsFunctions/arm_mean_f32.o \
./FFT/Source/StatisticsFunctions/arm_mean_f64.o \
./FFT/Source/StatisticsFunctions/arm_mean_q15.o \
./FFT/Source/StatisticsFunctions/arm_mean_q31.o \
./FFT/Source/StatisticsFunctions/arm_mean_q7.o \
./FFT/Source/StatisticsFunctions/arm_min_f16.o \
./FFT/Source/StatisticsFunctions/arm_min_f32.o \
./FFT/Source/StatisticsFunctions/arm_min_f64.o \
./FFT/Source/StatisticsFunctions/arm_min_no_idx_f16.o \
./FFT/Source/StatisticsFunctions/arm_min_no_idx_f32.o \
./FFT/Source/StatisticsFunctions/arm_min_no_idx_f64.o \
./FFT/Source/StatisticsFunctions/arm_min_no_idx_q15.o \
./FFT/Source/StatisticsFunctions/arm_min_no_idx_q31.o \
./FFT/Source/StatisticsFunctions/arm_min_no_idx_q7.o \
./FFT/Source/StatisticsFunctions/arm_min_q15.o \
./FFT/Source/StatisticsFunctions/arm_min_q31.o \
./FFT/Source/StatisticsFunctions/arm_min_q7.o \
./FFT/Source/StatisticsFunctions/arm_mse_f16.o \
./FFT/Source/StatisticsFunctions/arm_mse_f32.o \
./FFT/Source/StatisticsFunctions/arm_mse_f64.o \
./FFT/Source/StatisticsFunctions/arm_mse_q15.o \
./FFT/Source/StatisticsFunctions/arm_mse_q31.o \
./FFT/Source/StatisticsFunctions/arm_mse_q7.o \
./FFT/Source/StatisticsFunctions/arm_power_f16.o \
./FFT/Source/StatisticsFunctions/arm_power_f32.o \
./FFT/Source/StatisticsFunctions/arm_power_f64.o \
./FFT/Source/StatisticsFunctions/arm_power_q15.o \
./FFT/Source/StatisticsFunctions/arm_power_q31.o \
./FFT/Source/StatisticsFunctions/arm_power_q7.o \
./FFT/Source/StatisticsFunctions/arm_rms_f16.o \
./FFT/Source/StatisticsFunctions/arm_rms_f32.o \
./FFT/Source/StatisticsFunctions/arm_rms_q15.o \
./FFT/Source/StatisticsFunctions/arm_rms_q31.o \
./FFT/Source/StatisticsFunctions/arm_std_f16.o \
./FFT/Source/StatisticsFunctions/arm_std_f32.o \
./FFT/Source/StatisticsFunctions/arm_std_f64.o \
./FFT/Source/StatisticsFunctions/arm_std_q15.o \
./FFT/Source/StatisticsFunctions/arm_std_q31.o \
./FFT/Source/StatisticsFunctions/arm_var_f16.o \
./FFT/Source/StatisticsFunctions/arm_var_f32.o \
./FFT/Source/StatisticsFunctions/arm_var_f64.o \
./FFT/Source/StatisticsFunctions/arm_var_q15.o \
./FFT/Source/StatisticsFunctions/arm_var_q31.o 

C_DEPS += \
./FFT/Source/StatisticsFunctions/StatisticsFunctions.d \
./FFT/Source/StatisticsFunctions/StatisticsFunctionsF16.d \
./FFT/Source/StatisticsFunctions/arm_absmax_f16.d \
./FFT/Source/StatisticsFunctions/arm_absmax_f32.d \
./FFT/Source/StatisticsFunctions/arm_absmax_f64.d \
./FFT/Source/StatisticsFunctions/arm_absmax_no_idx_f16.d \
./FFT/Source/StatisticsFunctions/arm_absmax_no_idx_f32.d \
./FFT/Source/StatisticsFunctions/arm_absmax_no_idx_f64.d \
./FFT/Source/StatisticsFunctions/arm_absmax_no_idx_q15.d \
./FFT/Source/StatisticsFunctions/arm_absmax_no_idx_q31.d \
./FFT/Source/StatisticsFunctions/arm_absmax_no_idx_q7.d \
./FFT/Source/StatisticsFunctions/arm_absmax_q15.d \
./FFT/Source/StatisticsFunctions/arm_absmax_q31.d \
./FFT/Source/StatisticsFunctions/arm_absmax_q7.d \
./FFT/Source/StatisticsFunctions/arm_absmin_f16.d \
./FFT/Source/StatisticsFunctions/arm_absmin_f32.d \
./FFT/Source/StatisticsFunctions/arm_absmin_f64.d \
./FFT/Source/StatisticsFunctions/arm_absmin_no_idx_f16.d \
./FFT/Source/StatisticsFunctions/arm_absmin_no_idx_f32.d \
./FFT/Source/StatisticsFunctions/arm_absmin_no_idx_f64.d \
./FFT/Source/StatisticsFunctions/arm_absmin_no_idx_q15.d \
./FFT/Source/StatisticsFunctions/arm_absmin_no_idx_q31.d \
./FFT/Source/StatisticsFunctions/arm_absmin_no_idx_q7.d \
./FFT/Source/StatisticsFunctions/arm_absmin_q15.d \
./FFT/Source/StatisticsFunctions/arm_absmin_q31.d \
./FFT/Source/StatisticsFunctions/arm_absmin_q7.d \
./FFT/Source/StatisticsFunctions/arm_accumulate_f16.d \
./FFT/Source/StatisticsFunctions/arm_accumulate_f32.d \
./FFT/Source/StatisticsFunctions/arm_accumulate_f64.d \
./FFT/Source/StatisticsFunctions/arm_entropy_f16.d \
./FFT/Source/StatisticsFunctions/arm_entropy_f32.d \
./FFT/Source/StatisticsFunctions/arm_entropy_f64.d \
./FFT/Source/StatisticsFunctions/arm_kullback_leibler_f16.d \
./FFT/Source/StatisticsFunctions/arm_kullback_leibler_f32.d \
./FFT/Source/StatisticsFunctions/arm_kullback_leibler_f64.d \
./FFT/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.d \
./FFT/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.d \
./FFT/Source/StatisticsFunctions/arm_logsumexp_f16.d \
./FFT/Source/StatisticsFunctions/arm_logsumexp_f32.d \
./FFT/Source/StatisticsFunctions/arm_max_f16.d \
./FFT/Source/StatisticsFunctions/arm_max_f32.d \
./FFT/Source/StatisticsFunctions/arm_max_f64.d \
./FFT/Source/StatisticsFunctions/arm_max_no_idx_f16.d \
./FFT/Source/StatisticsFunctions/arm_max_no_idx_f32.d \
./FFT/Source/StatisticsFunctions/arm_max_no_idx_f64.d \
./FFT/Source/StatisticsFunctions/arm_max_no_idx_q15.d \
./FFT/Source/StatisticsFunctions/arm_max_no_idx_q31.d \
./FFT/Source/StatisticsFunctions/arm_max_no_idx_q7.d \
./FFT/Source/StatisticsFunctions/arm_max_q15.d \
./FFT/Source/StatisticsFunctions/arm_max_q31.d \
./FFT/Source/StatisticsFunctions/arm_max_q7.d \
./FFT/Source/StatisticsFunctions/arm_mean_f16.d \
./FFT/Source/StatisticsFunctions/arm_mean_f32.d \
./FFT/Source/StatisticsFunctions/arm_mean_f64.d \
./FFT/Source/StatisticsFunctions/arm_mean_q15.d \
./FFT/Source/StatisticsFunctions/arm_mean_q31.d \
./FFT/Source/StatisticsFunctions/arm_mean_q7.d \
./FFT/Source/StatisticsFunctions/arm_min_f16.d \
./FFT/Source/StatisticsFunctions/arm_min_f32.d \
./FFT/Source/StatisticsFunctions/arm_min_f64.d \
./FFT/Source/StatisticsFunctions/arm_min_no_idx_f16.d \
./FFT/Source/StatisticsFunctions/arm_min_no_idx_f32.d \
./FFT/Source/StatisticsFunctions/arm_min_no_idx_f64.d \
./FFT/Source/StatisticsFunctions/arm_min_no_idx_q15.d \
./FFT/Source/StatisticsFunctions/arm_min_no_idx_q31.d \
./FFT/Source/StatisticsFunctions/arm_min_no_idx_q7.d \
./FFT/Source/StatisticsFunctions/arm_min_q15.d \
./FFT/Source/StatisticsFunctions/arm_min_q31.d \
./FFT/Source/StatisticsFunctions/arm_min_q7.d \
./FFT/Source/StatisticsFunctions/arm_mse_f16.d \
./FFT/Source/StatisticsFunctions/arm_mse_f32.d \
./FFT/Source/StatisticsFunctions/arm_mse_f64.d \
./FFT/Source/StatisticsFunctions/arm_mse_q15.d \
./FFT/Source/StatisticsFunctions/arm_mse_q31.d \
./FFT/Source/StatisticsFunctions/arm_mse_q7.d \
./FFT/Source/StatisticsFunctions/arm_power_f16.d \
./FFT/Source/StatisticsFunctions/arm_power_f32.d \
./FFT/Source/StatisticsFunctions/arm_power_f64.d \
./FFT/Source/StatisticsFunctions/arm_power_q15.d \
./FFT/Source/StatisticsFunctions/arm_power_q31.d \
./FFT/Source/StatisticsFunctions/arm_power_q7.d \
./FFT/Source/StatisticsFunctions/arm_rms_f16.d \
./FFT/Source/StatisticsFunctions/arm_rms_f32.d \
./FFT/Source/StatisticsFunctions/arm_rms_q15.d \
./FFT/Source/StatisticsFunctions/arm_rms_q31.d \
./FFT/Source/StatisticsFunctions/arm_std_f16.d \
./FFT/Source/StatisticsFunctions/arm_std_f32.d \
./FFT/Source/StatisticsFunctions/arm_std_f64.d \
./FFT/Source/StatisticsFunctions/arm_std_q15.d \
./FFT/Source/StatisticsFunctions/arm_std_q31.d \
./FFT/Source/StatisticsFunctions/arm_var_f16.d \
./FFT/Source/StatisticsFunctions/arm_var_f32.d \
./FFT/Source/StatisticsFunctions/arm_var_f64.d \
./FFT/Source/StatisticsFunctions/arm_var_q15.d \
./FFT/Source/StatisticsFunctions/arm_var_q31.d 


# Each subdirectory must supply rules for building sources it contributes
FFT/Source/StatisticsFunctions/%.o FFT/Source/StatisticsFunctions/%.su FFT/Source/StatisticsFunctions/%.cyclo: ../FFT/Source/StatisticsFunctions/%.c FFT/Source/StatisticsFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U5A5xx -c -I../../Core/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I"C:/Users/raphael.baumeler/workspace_STM/200_Pinbelegung/STM32CubeIDE/Daten" -I"C:/Users/raphael.baumeler/workspace_STM/200_Pinbelegung/STM32CubeIDE/FFT/Include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-FFT-2f-Source-2f-StatisticsFunctions

clean-FFT-2f-Source-2f-StatisticsFunctions:
	-$(RM) ./FFT/Source/StatisticsFunctions/StatisticsFunctions.cyclo ./FFT/Source/StatisticsFunctions/StatisticsFunctions.d ./FFT/Source/StatisticsFunctions/StatisticsFunctions.o ./FFT/Source/StatisticsFunctions/StatisticsFunctions.su ./FFT/Source/StatisticsFunctions/StatisticsFunctionsF16.cyclo ./FFT/Source/StatisticsFunctions/StatisticsFunctionsF16.d ./FFT/Source/StatisticsFunctions/StatisticsFunctionsF16.o ./FFT/Source/StatisticsFunctions/StatisticsFunctionsF16.su ./FFT/Source/StatisticsFunctions/arm_absmax_f16.cyclo ./FFT/Source/StatisticsFunctions/arm_absmax_f16.d ./FFT/Source/StatisticsFunctions/arm_absmax_f16.o ./FFT/Source/StatisticsFunctions/arm_absmax_f16.su ./FFT/Source/StatisticsFunctions/arm_absmax_f32.cyclo ./FFT/Source/StatisticsFunctions/arm_absmax_f32.d ./FFT/Source/StatisticsFunctions/arm_absmax_f32.o ./FFT/Source/StatisticsFunctions/arm_absmax_f32.su ./FFT/Source/StatisticsFunctions/arm_absmax_f64.cyclo ./FFT/Source/StatisticsFunctions/arm_absmax_f64.d ./FFT/Source/StatisticsFunctions/arm_absmax_f64.o ./FFT/Source/StatisticsFunctions/arm_absmax_f64.su ./FFT/Source/StatisticsFunctions/arm_absmax_no_idx_f16.cyclo ./FFT/Source/StatisticsFunctions/arm_absmax_no_idx_f16.d ./FFT/Source/StatisticsFunctions/arm_absmax_no_idx_f16.o ./FFT/Source/StatisticsFunctions/arm_absmax_no_idx_f16.su ./FFT/Source/StatisticsFunctions/arm_absmax_no_idx_f32.cyclo ./FFT/Source/StatisticsFunctions/arm_absmax_no_idx_f32.d ./FFT/Source/StatisticsFunctions/arm_absmax_no_idx_f32.o ./FFT/Source/StatisticsFunctions/arm_absmax_no_idx_f32.su ./FFT/Source/StatisticsFunctions/arm_absmax_no_idx_f64.cyclo ./FFT/Source/StatisticsFunctions/arm_absmax_no_idx_f64.d ./FFT/Source/StatisticsFunctions/arm_absmax_no_idx_f64.o ./FFT/Source/StatisticsFunctions/arm_absmax_no_idx_f64.su ./FFT/Source/StatisticsFunctions/arm_absmax_no_idx_q15.cyclo ./FFT/Source/StatisticsFunctions/arm_absmax_no_idx_q15.d ./FFT/Source/StatisticsFunctions/arm_absmax_no_idx_q15.o ./FFT/Source/StatisticsFunctions/arm_absmax_no_idx_q15.su ./FFT/Source/StatisticsFunctions/arm_absmax_no_idx_q31.cyclo ./FFT/Source/StatisticsFunctions/arm_absmax_no_idx_q31.d ./FFT/Source/StatisticsFunctions/arm_absmax_no_idx_q31.o ./FFT/Source/StatisticsFunctions/arm_absmax_no_idx_q31.su ./FFT/Source/StatisticsFunctions/arm_absmax_no_idx_q7.cyclo ./FFT/Source/StatisticsFunctions/arm_absmax_no_idx_q7.d ./FFT/Source/StatisticsFunctions/arm_absmax_no_idx_q7.o ./FFT/Source/StatisticsFunctions/arm_absmax_no_idx_q7.su ./FFT/Source/StatisticsFunctions/arm_absmax_q15.cyclo ./FFT/Source/StatisticsFunctions/arm_absmax_q15.d ./FFT/Source/StatisticsFunctions/arm_absmax_q15.o ./FFT/Source/StatisticsFunctions/arm_absmax_q15.su ./FFT/Source/StatisticsFunctions/arm_absmax_q31.cyclo ./FFT/Source/StatisticsFunctions/arm_absmax_q31.d ./FFT/Source/StatisticsFunctions/arm_absmax_q31.o ./FFT/Source/StatisticsFunctions/arm_absmax_q31.su ./FFT/Source/StatisticsFunctions/arm_absmax_q7.cyclo ./FFT/Source/StatisticsFunctions/arm_absmax_q7.d ./FFT/Source/StatisticsFunctions/arm_absmax_q7.o ./FFT/Source/StatisticsFunctions/arm_absmax_q7.su ./FFT/Source/StatisticsFunctions/arm_absmin_f16.cyclo ./FFT/Source/StatisticsFunctions/arm_absmin_f16.d ./FFT/Source/StatisticsFunctions/arm_absmin_f16.o ./FFT/Source/StatisticsFunctions/arm_absmin_f16.su ./FFT/Source/StatisticsFunctions/arm_absmin_f32.cyclo ./FFT/Source/StatisticsFunctions/arm_absmin_f32.d ./FFT/Source/StatisticsFunctions/arm_absmin_f32.o ./FFT/Source/StatisticsFunctions/arm_absmin_f32.su ./FFT/Source/StatisticsFunctions/arm_absmin_f64.cyclo ./FFT/Source/StatisticsFunctions/arm_absmin_f64.d ./FFT/Source/StatisticsFunctions/arm_absmin_f64.o ./FFT/Source/StatisticsFunctions/arm_absmin_f64.su ./FFT/Source/StatisticsFunctions/arm_absmin_no_idx_f16.cyclo ./FFT/Source/StatisticsFunctions/arm_absmin_no_idx_f16.d ./FFT/Source/StatisticsFunctions/arm_absmin_no_idx_f16.o ./FFT/Source/StatisticsFunctions/arm_absmin_no_idx_f16.su ./FFT/Source/StatisticsFunctions/arm_absmin_no_idx_f32.cyclo ./FFT/Source/StatisticsFunctions/arm_absmin_no_idx_f32.d ./FFT/Source/StatisticsFunctions/arm_absmin_no_idx_f32.o ./FFT/Source/StatisticsFunctions/arm_absmin_no_idx_f32.su ./FFT/Source/StatisticsFunctions/arm_absmin_no_idx_f64.cyclo ./FFT/Source/StatisticsFunctions/arm_absmin_no_idx_f64.d ./FFT/Source/StatisticsFunctions/arm_absmin_no_idx_f64.o ./FFT/Source/StatisticsFunctions/arm_absmin_no_idx_f64.su ./FFT/Source/StatisticsFunctions/arm_absmin_no_idx_q15.cyclo ./FFT/Source/StatisticsFunctions/arm_absmin_no_idx_q15.d ./FFT/Source/StatisticsFunctions/arm_absmin_no_idx_q15.o ./FFT/Source/StatisticsFunctions/arm_absmin_no_idx_q15.su ./FFT/Source/StatisticsFunctions/arm_absmin_no_idx_q31.cyclo ./FFT/Source/StatisticsFunctions/arm_absmin_no_idx_q31.d ./FFT/Source/StatisticsFunctions/arm_absmin_no_idx_q31.o ./FFT/Source/StatisticsFunctions/arm_absmin_no_idx_q31.su ./FFT/Source/StatisticsFunctions/arm_absmin_no_idx_q7.cyclo ./FFT/Source/StatisticsFunctions/arm_absmin_no_idx_q7.d ./FFT/Source/StatisticsFunctions/arm_absmin_no_idx_q7.o ./FFT/Source/StatisticsFunctions/arm_absmin_no_idx_q7.su ./FFT/Source/StatisticsFunctions/arm_absmin_q15.cyclo ./FFT/Source/StatisticsFunctions/arm_absmin_q15.d ./FFT/Source/StatisticsFunctions/arm_absmin_q15.o ./FFT/Source/StatisticsFunctions/arm_absmin_q15.su ./FFT/Source/StatisticsFunctions/arm_absmin_q31.cyclo ./FFT/Source/StatisticsFunctions/arm_absmin_q31.d ./FFT/Source/StatisticsFunctions/arm_absmin_q31.o ./FFT/Source/StatisticsFunctions/arm_absmin_q31.su ./FFT/Source/StatisticsFunctions/arm_absmin_q7.cyclo ./FFT/Source/StatisticsFunctions/arm_absmin_q7.d ./FFT/Source/StatisticsFunctions/arm_absmin_q7.o ./FFT/Source/StatisticsFunctions/arm_absmin_q7.su ./FFT/Source/StatisticsFunctions/arm_accumulate_f16.cyclo ./FFT/Source/StatisticsFunctions/arm_accumulate_f16.d ./FFT/Source/StatisticsFunctions/arm_accumulate_f16.o ./FFT/Source/StatisticsFunctions/arm_accumulate_f16.su ./FFT/Source/StatisticsFunctions/arm_accumulate_f32.cyclo
	-$(RM) ./FFT/Source/StatisticsFunctions/arm_accumulate_f32.d ./FFT/Source/StatisticsFunctions/arm_accumulate_f32.o ./FFT/Source/StatisticsFunctions/arm_accumulate_f32.su ./FFT/Source/StatisticsFunctions/arm_accumulate_f64.cyclo ./FFT/Source/StatisticsFunctions/arm_accumulate_f64.d ./FFT/Source/StatisticsFunctions/arm_accumulate_f64.o ./FFT/Source/StatisticsFunctions/arm_accumulate_f64.su ./FFT/Source/StatisticsFunctions/arm_entropy_f16.cyclo ./FFT/Source/StatisticsFunctions/arm_entropy_f16.d ./FFT/Source/StatisticsFunctions/arm_entropy_f16.o ./FFT/Source/StatisticsFunctions/arm_entropy_f16.su ./FFT/Source/StatisticsFunctions/arm_entropy_f32.cyclo ./FFT/Source/StatisticsFunctions/arm_entropy_f32.d ./FFT/Source/StatisticsFunctions/arm_entropy_f32.o ./FFT/Source/StatisticsFunctions/arm_entropy_f32.su ./FFT/Source/StatisticsFunctions/arm_entropy_f64.cyclo ./FFT/Source/StatisticsFunctions/arm_entropy_f64.d ./FFT/Source/StatisticsFunctions/arm_entropy_f64.o ./FFT/Source/StatisticsFunctions/arm_entropy_f64.su ./FFT/Source/StatisticsFunctions/arm_kullback_leibler_f16.cyclo ./FFT/Source/StatisticsFunctions/arm_kullback_leibler_f16.d ./FFT/Source/StatisticsFunctions/arm_kullback_leibler_f16.o ./FFT/Source/StatisticsFunctions/arm_kullback_leibler_f16.su ./FFT/Source/StatisticsFunctions/arm_kullback_leibler_f32.cyclo ./FFT/Source/StatisticsFunctions/arm_kullback_leibler_f32.d ./FFT/Source/StatisticsFunctions/arm_kullback_leibler_f32.o ./FFT/Source/StatisticsFunctions/arm_kullback_leibler_f32.su ./FFT/Source/StatisticsFunctions/arm_kullback_leibler_f64.cyclo ./FFT/Source/StatisticsFunctions/arm_kullback_leibler_f64.d ./FFT/Source/StatisticsFunctions/arm_kullback_leibler_f64.o ./FFT/Source/StatisticsFunctions/arm_kullback_leibler_f64.su ./FFT/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.cyclo ./FFT/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.d ./FFT/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.o ./FFT/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.su ./FFT/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.cyclo ./FFT/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.d ./FFT/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.o ./FFT/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.su ./FFT/Source/StatisticsFunctions/arm_logsumexp_f16.cyclo ./FFT/Source/StatisticsFunctions/arm_logsumexp_f16.d ./FFT/Source/StatisticsFunctions/arm_logsumexp_f16.o ./FFT/Source/StatisticsFunctions/arm_logsumexp_f16.su ./FFT/Source/StatisticsFunctions/arm_logsumexp_f32.cyclo ./FFT/Source/StatisticsFunctions/arm_logsumexp_f32.d ./FFT/Source/StatisticsFunctions/arm_logsumexp_f32.o ./FFT/Source/StatisticsFunctions/arm_logsumexp_f32.su ./FFT/Source/StatisticsFunctions/arm_max_f16.cyclo ./FFT/Source/StatisticsFunctions/arm_max_f16.d ./FFT/Source/StatisticsFunctions/arm_max_f16.o ./FFT/Source/StatisticsFunctions/arm_max_f16.su ./FFT/Source/StatisticsFunctions/arm_max_f32.cyclo ./FFT/Source/StatisticsFunctions/arm_max_f32.d ./FFT/Source/StatisticsFunctions/arm_max_f32.o ./FFT/Source/StatisticsFunctions/arm_max_f32.su ./FFT/Source/StatisticsFunctions/arm_max_f64.cyclo ./FFT/Source/StatisticsFunctions/arm_max_f64.d ./FFT/Source/StatisticsFunctions/arm_max_f64.o ./FFT/Source/StatisticsFunctions/arm_max_f64.su ./FFT/Source/StatisticsFunctions/arm_max_no_idx_f16.cyclo ./FFT/Source/StatisticsFunctions/arm_max_no_idx_f16.d ./FFT/Source/StatisticsFunctions/arm_max_no_idx_f16.o ./FFT/Source/StatisticsFunctions/arm_max_no_idx_f16.su ./FFT/Source/StatisticsFunctions/arm_max_no_idx_f32.cyclo ./FFT/Source/StatisticsFunctions/arm_max_no_idx_f32.d ./FFT/Source/StatisticsFunctions/arm_max_no_idx_f32.o ./FFT/Source/StatisticsFunctions/arm_max_no_idx_f32.su ./FFT/Source/StatisticsFunctions/arm_max_no_idx_f64.cyclo ./FFT/Source/StatisticsFunctions/arm_max_no_idx_f64.d ./FFT/Source/StatisticsFunctions/arm_max_no_idx_f64.o ./FFT/Source/StatisticsFunctions/arm_max_no_idx_f64.su ./FFT/Source/StatisticsFunctions/arm_max_no_idx_q15.cyclo ./FFT/Source/StatisticsFunctions/arm_max_no_idx_q15.d ./FFT/Source/StatisticsFunctions/arm_max_no_idx_q15.o ./FFT/Source/StatisticsFunctions/arm_max_no_idx_q15.su ./FFT/Source/StatisticsFunctions/arm_max_no_idx_q31.cyclo ./FFT/Source/StatisticsFunctions/arm_max_no_idx_q31.d ./FFT/Source/StatisticsFunctions/arm_max_no_idx_q31.o ./FFT/Source/StatisticsFunctions/arm_max_no_idx_q31.su ./FFT/Source/StatisticsFunctions/arm_max_no_idx_q7.cyclo ./FFT/Source/StatisticsFunctions/arm_max_no_idx_q7.d ./FFT/Source/StatisticsFunctions/arm_max_no_idx_q7.o ./FFT/Source/StatisticsFunctions/arm_max_no_idx_q7.su ./FFT/Source/StatisticsFunctions/arm_max_q15.cyclo ./FFT/Source/StatisticsFunctions/arm_max_q15.d ./FFT/Source/StatisticsFunctions/arm_max_q15.o ./FFT/Source/StatisticsFunctions/arm_max_q15.su ./FFT/Source/StatisticsFunctions/arm_max_q31.cyclo ./FFT/Source/StatisticsFunctions/arm_max_q31.d ./FFT/Source/StatisticsFunctions/arm_max_q31.o ./FFT/Source/StatisticsFunctions/arm_max_q31.su ./FFT/Source/StatisticsFunctions/arm_max_q7.cyclo ./FFT/Source/StatisticsFunctions/arm_max_q7.d ./FFT/Source/StatisticsFunctions/arm_max_q7.o ./FFT/Source/StatisticsFunctions/arm_max_q7.su ./FFT/Source/StatisticsFunctions/arm_mean_f16.cyclo ./FFT/Source/StatisticsFunctions/arm_mean_f16.d ./FFT/Source/StatisticsFunctions/arm_mean_f16.o ./FFT/Source/StatisticsFunctions/arm_mean_f16.su ./FFT/Source/StatisticsFunctions/arm_mean_f32.cyclo ./FFT/Source/StatisticsFunctions/arm_mean_f32.d ./FFT/Source/StatisticsFunctions/arm_mean_f32.o ./FFT/Source/StatisticsFunctions/arm_mean_f32.su ./FFT/Source/StatisticsFunctions/arm_mean_f64.cyclo ./FFT/Source/StatisticsFunctions/arm_mean_f64.d ./FFT/Source/StatisticsFunctions/arm_mean_f64.o ./FFT/Source/StatisticsFunctions/arm_mean_f64.su ./FFT/Source/StatisticsFunctions/arm_mean_q15.cyclo ./FFT/Source/StatisticsFunctions/arm_mean_q15.d ./FFT/Source/StatisticsFunctions/arm_mean_q15.o ./FFT/Source/StatisticsFunctions/arm_mean_q15.su
	-$(RM) ./FFT/Source/StatisticsFunctions/arm_mean_q31.cyclo ./FFT/Source/StatisticsFunctions/arm_mean_q31.d ./FFT/Source/StatisticsFunctions/arm_mean_q31.o ./FFT/Source/StatisticsFunctions/arm_mean_q31.su ./FFT/Source/StatisticsFunctions/arm_mean_q7.cyclo ./FFT/Source/StatisticsFunctions/arm_mean_q7.d ./FFT/Source/StatisticsFunctions/arm_mean_q7.o ./FFT/Source/StatisticsFunctions/arm_mean_q7.su ./FFT/Source/StatisticsFunctions/arm_min_f16.cyclo ./FFT/Source/StatisticsFunctions/arm_min_f16.d ./FFT/Source/StatisticsFunctions/arm_min_f16.o ./FFT/Source/StatisticsFunctions/arm_min_f16.su ./FFT/Source/StatisticsFunctions/arm_min_f32.cyclo ./FFT/Source/StatisticsFunctions/arm_min_f32.d ./FFT/Source/StatisticsFunctions/arm_min_f32.o ./FFT/Source/StatisticsFunctions/arm_min_f32.su ./FFT/Source/StatisticsFunctions/arm_min_f64.cyclo ./FFT/Source/StatisticsFunctions/arm_min_f64.d ./FFT/Source/StatisticsFunctions/arm_min_f64.o ./FFT/Source/StatisticsFunctions/arm_min_f64.su ./FFT/Source/StatisticsFunctions/arm_min_no_idx_f16.cyclo ./FFT/Source/StatisticsFunctions/arm_min_no_idx_f16.d ./FFT/Source/StatisticsFunctions/arm_min_no_idx_f16.o ./FFT/Source/StatisticsFunctions/arm_min_no_idx_f16.su ./FFT/Source/StatisticsFunctions/arm_min_no_idx_f32.cyclo ./FFT/Source/StatisticsFunctions/arm_min_no_idx_f32.d ./FFT/Source/StatisticsFunctions/arm_min_no_idx_f32.o ./FFT/Source/StatisticsFunctions/arm_min_no_idx_f32.su ./FFT/Source/StatisticsFunctions/arm_min_no_idx_f64.cyclo ./FFT/Source/StatisticsFunctions/arm_min_no_idx_f64.d ./FFT/Source/StatisticsFunctions/arm_min_no_idx_f64.o ./FFT/Source/StatisticsFunctions/arm_min_no_idx_f64.su ./FFT/Source/StatisticsFunctions/arm_min_no_idx_q15.cyclo ./FFT/Source/StatisticsFunctions/arm_min_no_idx_q15.d ./FFT/Source/StatisticsFunctions/arm_min_no_idx_q15.o ./FFT/Source/StatisticsFunctions/arm_min_no_idx_q15.su ./FFT/Source/StatisticsFunctions/arm_min_no_idx_q31.cyclo ./FFT/Source/StatisticsFunctions/arm_min_no_idx_q31.d ./FFT/Source/StatisticsFunctions/arm_min_no_idx_q31.o ./FFT/Source/StatisticsFunctions/arm_min_no_idx_q31.su ./FFT/Source/StatisticsFunctions/arm_min_no_idx_q7.cyclo ./FFT/Source/StatisticsFunctions/arm_min_no_idx_q7.d ./FFT/Source/StatisticsFunctions/arm_min_no_idx_q7.o ./FFT/Source/StatisticsFunctions/arm_min_no_idx_q7.su ./FFT/Source/StatisticsFunctions/arm_min_q15.cyclo ./FFT/Source/StatisticsFunctions/arm_min_q15.d ./FFT/Source/StatisticsFunctions/arm_min_q15.o ./FFT/Source/StatisticsFunctions/arm_min_q15.su ./FFT/Source/StatisticsFunctions/arm_min_q31.cyclo ./FFT/Source/StatisticsFunctions/arm_min_q31.d ./FFT/Source/StatisticsFunctions/arm_min_q31.o ./FFT/Source/StatisticsFunctions/arm_min_q31.su ./FFT/Source/StatisticsFunctions/arm_min_q7.cyclo ./FFT/Source/StatisticsFunctions/arm_min_q7.d ./FFT/Source/StatisticsFunctions/arm_min_q7.o ./FFT/Source/StatisticsFunctions/arm_min_q7.su ./FFT/Source/StatisticsFunctions/arm_mse_f16.cyclo ./FFT/Source/StatisticsFunctions/arm_mse_f16.d ./FFT/Source/StatisticsFunctions/arm_mse_f16.o ./FFT/Source/StatisticsFunctions/arm_mse_f16.su ./FFT/Source/StatisticsFunctions/arm_mse_f32.cyclo ./FFT/Source/StatisticsFunctions/arm_mse_f32.d ./FFT/Source/StatisticsFunctions/arm_mse_f32.o ./FFT/Source/StatisticsFunctions/arm_mse_f32.su ./FFT/Source/StatisticsFunctions/arm_mse_f64.cyclo ./FFT/Source/StatisticsFunctions/arm_mse_f64.d ./FFT/Source/StatisticsFunctions/arm_mse_f64.o ./FFT/Source/StatisticsFunctions/arm_mse_f64.su ./FFT/Source/StatisticsFunctions/arm_mse_q15.cyclo ./FFT/Source/StatisticsFunctions/arm_mse_q15.d ./FFT/Source/StatisticsFunctions/arm_mse_q15.o ./FFT/Source/StatisticsFunctions/arm_mse_q15.su ./FFT/Source/StatisticsFunctions/arm_mse_q31.cyclo ./FFT/Source/StatisticsFunctions/arm_mse_q31.d ./FFT/Source/StatisticsFunctions/arm_mse_q31.o ./FFT/Source/StatisticsFunctions/arm_mse_q31.su ./FFT/Source/StatisticsFunctions/arm_mse_q7.cyclo ./FFT/Source/StatisticsFunctions/arm_mse_q7.d ./FFT/Source/StatisticsFunctions/arm_mse_q7.o ./FFT/Source/StatisticsFunctions/arm_mse_q7.su ./FFT/Source/StatisticsFunctions/arm_power_f16.cyclo ./FFT/Source/StatisticsFunctions/arm_power_f16.d ./FFT/Source/StatisticsFunctions/arm_power_f16.o ./FFT/Source/StatisticsFunctions/arm_power_f16.su ./FFT/Source/StatisticsFunctions/arm_power_f32.cyclo ./FFT/Source/StatisticsFunctions/arm_power_f32.d ./FFT/Source/StatisticsFunctions/arm_power_f32.o ./FFT/Source/StatisticsFunctions/arm_power_f32.su ./FFT/Source/StatisticsFunctions/arm_power_f64.cyclo ./FFT/Source/StatisticsFunctions/arm_power_f64.d ./FFT/Source/StatisticsFunctions/arm_power_f64.o ./FFT/Source/StatisticsFunctions/arm_power_f64.su ./FFT/Source/StatisticsFunctions/arm_power_q15.cyclo ./FFT/Source/StatisticsFunctions/arm_power_q15.d ./FFT/Source/StatisticsFunctions/arm_power_q15.o ./FFT/Source/StatisticsFunctions/arm_power_q15.su ./FFT/Source/StatisticsFunctions/arm_power_q31.cyclo ./FFT/Source/StatisticsFunctions/arm_power_q31.d ./FFT/Source/StatisticsFunctions/arm_power_q31.o ./FFT/Source/StatisticsFunctions/arm_power_q31.su ./FFT/Source/StatisticsFunctions/arm_power_q7.cyclo ./FFT/Source/StatisticsFunctions/arm_power_q7.d ./FFT/Source/StatisticsFunctions/arm_power_q7.o ./FFT/Source/StatisticsFunctions/arm_power_q7.su ./FFT/Source/StatisticsFunctions/arm_rms_f16.cyclo ./FFT/Source/StatisticsFunctions/arm_rms_f16.d ./FFT/Source/StatisticsFunctions/arm_rms_f16.o ./FFT/Source/StatisticsFunctions/arm_rms_f16.su ./FFT/Source/StatisticsFunctions/arm_rms_f32.cyclo ./FFT/Source/StatisticsFunctions/arm_rms_f32.d ./FFT/Source/StatisticsFunctions/arm_rms_f32.o ./FFT/Source/StatisticsFunctions/arm_rms_f32.su ./FFT/Source/StatisticsFunctions/arm_rms_q15.cyclo ./FFT/Source/StatisticsFunctions/arm_rms_q15.d ./FFT/Source/StatisticsFunctions/arm_rms_q15.o ./FFT/Source/StatisticsFunctions/arm_rms_q15.su ./FFT/Source/StatisticsFunctions/arm_rms_q31.cyclo ./FFT/Source/StatisticsFunctions/arm_rms_q31.d ./FFT/Source/StatisticsFunctions/arm_rms_q31.o ./FFT/Source/StatisticsFunctions/arm_rms_q31.su
	-$(RM) ./FFT/Source/StatisticsFunctions/arm_std_f16.cyclo ./FFT/Source/StatisticsFunctions/arm_std_f16.d ./FFT/Source/StatisticsFunctions/arm_std_f16.o ./FFT/Source/StatisticsFunctions/arm_std_f16.su ./FFT/Source/StatisticsFunctions/arm_std_f32.cyclo ./FFT/Source/StatisticsFunctions/arm_std_f32.d ./FFT/Source/StatisticsFunctions/arm_std_f32.o ./FFT/Source/StatisticsFunctions/arm_std_f32.su ./FFT/Source/StatisticsFunctions/arm_std_f64.cyclo ./FFT/Source/StatisticsFunctions/arm_std_f64.d ./FFT/Source/StatisticsFunctions/arm_std_f64.o ./FFT/Source/StatisticsFunctions/arm_std_f64.su ./FFT/Source/StatisticsFunctions/arm_std_q15.cyclo ./FFT/Source/StatisticsFunctions/arm_std_q15.d ./FFT/Source/StatisticsFunctions/arm_std_q15.o ./FFT/Source/StatisticsFunctions/arm_std_q15.su ./FFT/Source/StatisticsFunctions/arm_std_q31.cyclo ./FFT/Source/StatisticsFunctions/arm_std_q31.d ./FFT/Source/StatisticsFunctions/arm_std_q31.o ./FFT/Source/StatisticsFunctions/arm_std_q31.su ./FFT/Source/StatisticsFunctions/arm_var_f16.cyclo ./FFT/Source/StatisticsFunctions/arm_var_f16.d ./FFT/Source/StatisticsFunctions/arm_var_f16.o ./FFT/Source/StatisticsFunctions/arm_var_f16.su ./FFT/Source/StatisticsFunctions/arm_var_f32.cyclo ./FFT/Source/StatisticsFunctions/arm_var_f32.d ./FFT/Source/StatisticsFunctions/arm_var_f32.o ./FFT/Source/StatisticsFunctions/arm_var_f32.su ./FFT/Source/StatisticsFunctions/arm_var_f64.cyclo ./FFT/Source/StatisticsFunctions/arm_var_f64.d ./FFT/Source/StatisticsFunctions/arm_var_f64.o ./FFT/Source/StatisticsFunctions/arm_var_f64.su ./FFT/Source/StatisticsFunctions/arm_var_q15.cyclo ./FFT/Source/StatisticsFunctions/arm_var_q15.d ./FFT/Source/StatisticsFunctions/arm_var_q15.o ./FFT/Source/StatisticsFunctions/arm_var_q15.su ./FFT/Source/StatisticsFunctions/arm_var_q31.cyclo ./FFT/Source/StatisticsFunctions/arm_var_q31.d ./FFT/Source/StatisticsFunctions/arm_var_q31.o ./FFT/Source/StatisticsFunctions/arm_var_q31.su

.PHONY: clean-FFT-2f-Source-2f-StatisticsFunctions

